// Vendored from vali-rs @ e70fadd. Do not edit; regenerate instead.

pub static COUNTRY_NAMES: &[(&str, &str)] = &[
    ("AE", "United Arab Emirates"),
    ("AF", "Afghanistan"),
    ("AL", "Albania"),
    ("AM", "Armenia"),
    ("AR", "Argentina"),
    ("AT", "Austria"),
    ("AU", "Australia"),
    ("AZ", "Azerbaijan"),
    ("BA", "Bosnia and Herzegovina"),
    ("BD", "Bangladesh"),
    ("BE", "Belgium"),
    ("BG", "Bulgaria"),
    ("BH", "Bahrain"),
    ("BN", "Brunei"),
    ("BO", "Bolivia"),
    ("BR", "Brazil"),
    ("BT", "Bhutan"),
    ("BW", "Botswana"),
    ("BY", "Belarus"),
    ("BZ", "Belize"),
    ("CA", "Canada"),
    ("CD", "Democratic Republic of the Congo"),
    ("CH", "Switzerland"),
    ("CI", "Côte d'Ivoire"),
    ("CL", "Chile"),
    ("CM", "Cameroon"),
    ("CN", "China"),
    ("CO", "Colombia"),
    ("CR", "Costa Rica"),
    ("CU", "Cuba"),
    ("CZ", "Czechia"),
    ("DE", "Germany"),
    ("DK", "Denmark"),
    ("DO", "Dominican Republic"),
    ("DZ", "Algeria"),
    ("EC", "Ecuador"),
    ("EE", "Estonia"),
    ("EG", "Egypt"),
    ("ER", "Eritrea"),
    ("ES", "Spain"),
    ("ET", "Ethiopia"),
    ("FI", "Finland"),
    ("FO", "Faroe Islands"),
    ("FR", "France"),
    ("GB", "United Kingdom"),
    ("GE", "Georgia"),
    ("GL", "Greenland"),
    ("GR", "Greece"),
    ("GT", "Guatemala"),
    ("HK", "Hong Kong"),
    ("HN", "Honduras"),
    ("HR", "Croatia"),
    ("HT", "Haiti"),
    ("HU", "Hungary"),
    ("ID", "Indonesia"),
    ("IE", "Ireland"),
    ("IL", "Israel"),
    ("IN", "India"),
    ("IQ", "Iraq"),
    ("IR", "Iran"),
    ("IS", "Iceland"),
    ("IT", "Italy"),
    ("JM", "Jamaica"),
    ("JO", "Jordan"),
    ("JP", "Japan"),
    ("KE", "Kenya"),
    ("KG", "Kyrgyzstan"),
    ("KH", "Cambodia"),
    ("KR", "South Korea"),
    ("KW", "Kuwait"),
    ("KZ", "Kazakhstan"),
    ("LA", "Laos"),
    ("LB", "Lebanon"),
    ("LI", "Liechtenstein"),
    ("LK", "Sri Lanka"),
    ("LT", "Lithuania"),
    ("LU", "Luxembourg"),
    ("LV", "Latvia"),
    ("LY", "Libya"),
    ("MA", "Morocco"),
    ("MC", "Monaco"),
    ("MD", "Moldova"),
    ("ME", "Montenegro"),
    ("MK", "North Macedonia"),
    ("ML", "Mali"),
    ("MM", "Myanmar"),
    ("MN", "Mongolia"),
    ("MO", "Macao"),
    ("MT", "Malta"),
    ("MV", "Maldives"),
    ("MX", "Mexico"),
    ("MY", "Malaysia"),
    ("NG", "Nigeria"),
    ("NI", "Nicaragua"),
    ("NL", "Netherlands"),
    ("NO", "Norway"),
    ("NP", "Nepal"),
    ("NZ", "New Zealand"),
    ("OM", "Oman"),
    ("PA", "Panama"),
    ("PE", "Peru"),
    ("PH", "Philippines"),
    ("PK", "Pakistan"),
    ("PL", "Poland"),
    ("PR", "Puerto Rico"),
    ("PT", "Portugal"),
    ("PY", "Paraguay"),
    ("QA", "Qatar"),
    ("RE", "Réunion"),
    ("RO", "Romania"),
    ("RS", "Serbia"),
    ("RU", "Russia"),
    ("RW", "Rwanda"),
    ("SA", "Saudi Arabia"),
    ("SE", "Sweden"),
    ("SG", "Singapore"),
    ("SI", "Slovenia"),
    ("SK", "Slovakia"),
    ("SN", "Senegal"),
    ("SO", "Somalia"),
    ("SV", "El Salvador"),
    ("SY", "Syria"),
    ("TH", "Thailand"),
    ("TJ", "Tajikistan"),
    ("TM", "Turkmenistan"),
    ("TN", "Tunisia"),
    ("TR", "Turkey"),
    ("TT", "Trinidad and Tobago"),
    ("TW", "Taiwan"),
    ("UA", "Ukraine"),
    ("US", "United States of America"),
    ("UY", "Uruguay"),
    ("UZ", "Uzbekistan"),
    ("VE", "Venezuela"),
    ("VN", "Vietnam"),
    ("YE", "Yemen"),
    ("ZA", "South Africa"),
    ("ZW", "Zimbabwe"),
    ("CW", "Curaçao"),
    ("AD", "Andorra"),
    ("AG", "Antigua and Barbuda"),
    ("AI", "Anguilla"),
    ("AO", "Angola"),
    ("AQ", "Antarctica"),
    ("AS", "American Samoa"),
    ("AW", "Aruba"),
    ("AX", "Åland Islands"),
    ("BB", "Barbados"),
    ("BF", "Burkina Faso"),
    ("BI", "Burundi"),
    ("BJ", "Benin"),
    ("BL", "Saint Barthélemy"),
    ("BM", "Bermuda"),
    ("BQ", "Bonaire, Sint Eustatius and Saba"),
    ("BS", "Bahamas"),
    ("BV", "Bouvet Island"),
    ("CC", "Cocos (Keeling) Islands"),
    ("CF", "Central African Republic"),
    ("CG", "The Congo"),
    ("CK", "Cook Islands"),
    ("CV", "Cabo Verde"),
    ("CX", "Christmas Island"),
    ("CY", "Cyprus"),
    ("DJ", "Djibouti"),
    ("DM", "Dominica"),
    ("EH", "Western Sahara"),
    ("FJ", "Fiji"),
    ("FK", "Falkland Islands"),
    ("FM", "Micronesia"),
    ("GA", "Gabon"),
    ("GD", "Grenada"),
    ("GF", "French Guiana"),
    ("GG", "Guernsey"),
    ("GH", "Ghana"),
    ("GI", "Gibraltar"),
    ("GM", "Gambia"),
    ("GN", "Guinea"),
    ("GP", "Guadeloupe"),
    ("GQ", "Equatorial Guinea"),
    ("GS", "South Georgia and the South Sandwich Islands"),
    ("GU", "Guam"),
    ("GW", "Guinea-Bissau"),
    ("GY", "Guyana"),
    ("HM", "Heard Island and McDonald Islands"),
    ("IM", "Isle of Man"),
    ("IO", "British Indian Ocean Territory"),
    ("JE", "Jersey"),
    ("KI", "Kiribati"),
    ("KM", "Comoros"),
    ("KN", "Saint Kitts and Nevis"),
    ("KP", "North Korea"),
    ("KY", "Cayman Islands"),
    ("LC", "Saint Lucia"),
    ("LR", "Liberia"),
    ("LS", "Lesotho"),
    ("MF", "Saint Martin"),
    ("MG", "Madagascar"),
    ("MH", "Marshall Islands"),
    ("MP", "Northern Mariana Islands"),
    ("MQ", "Martinique"),
    ("MR", "Mauritania"),
    ("MS", "Montserrat"),
    ("MU", "Mauritius"),
    ("MW", "Malawi"),
    ("MZ", "Mozambique"),
    ("NA", "Namibia"),
    ("NC", "New Caledonia"),
    ("NE", "Niger"),
    ("NF", "Norfolk Island"),
    ("NR", "Nauru"),
    ("NU", "Niue"),
    ("PF", "French Polynesia"),
    ("PG", "Papua New Guinea"),
    ("PM", "Saint Pierre and Miquelon"),
    ("PN", "Pitcairn"),
    ("PS", "State of Palestine"),
    ("PW", "Palau"),
    ("SB", "Solomon Islands"),
    ("SC", "Seychelles"),
    ("SD", "Sudan"),
    ("SH", "Saint Helena, Ascension and Tristan da Cunha"),
    ("SJ", "Svalbard and Jan Mayen"),
    ("SL", "Sierra Leone"),
    ("SM", "San Marino"),
    ("SR", "Suriname"),
    ("SS", "South Sudan"),
    ("ST", "Sao Tome and Principe"),
    ("SX", "Sint Maarten"),
    ("SZ", "Eswatini"),
    ("TC", "Turks and Caicos Islands"),
    ("TD", "Chad"),
    ("TF", "French Southern Territories"),
    ("TG", "Togo"),
    ("TK", "Tokelau"),
    ("TL", "East Timor"),
    ("TO", "Tonga"),
    ("TV", "Tuvalu"),
    ("TZ", "Tanzania"),
    ("UG", "Uganda"),
    ("UM", "United States Minor Outlying Islands"),
    ("VA", "Vatican City"),
    ("VC", "Saint Vincent and the Grenadines"),
    ("VG", "British Virgin Islands"),
    ("VI", "U.S. Virgin Islands"),
    ("VU", "Vanuatu"),
    ("WF", "Wallis and Futuna"),
    ("WS", "Samoa"),
    ("YT", "Mayotte"),
    ("ZM", "Zambia"),
];
pub static SUBDIVISION_NAMES: &[(&str, &[(&str, &str)])] = &[
    (
        "DK",
        &[
            ("DK-81", "North Denmark Region"),
            ("DK-82", "Region Midtjylland"),
            ("DK-83", "Region Syddanmark"),
            ("DK-84", "Region Hovedstaden"),
            ("DK-85", "Region Sjaelland"),
        ],
    ),
    (
        "NZ",
        &[
            ("NZ-AUK", "Auckland"),
            ("NZ-BOP", "Bay of Plenty"),
            ("NZ-CAN", "Canterbury"),
            ("NZ-GIS", "Gisborne"),
            ("NZ-HKB", "Hawke's Bay"),
            ("NZ-MBH", "Marlborough"),
            ("NZ-MWT", "Manawatu-Whanganui"),
            ("NZ-NSN", "Nelson"),
            ("NZ-NTL", "Northland"),
            ("NZ-OTA", "Otago"),
            ("NZ-STL", "Southland"),
            ("NZ-TAS", "Tasman"),
            ("NZ-TKI", "Taranaki"),
            ("NZ-WGN", "Greater Wellington"),
            ("NZ-WKO", "Waikato"),
            ("NZ-WTC", "West Coast"),
        ],
    ),
    (
        "NL",
        &[
            ("NL-DR", "Provincie Drenthe"),
            ("NL-FL", "Provincie Flevoland"),
            ("NL-FR", "Provincie Friesland"),
            ("NL-GE", "Provincie Gelderland"),
            ("NL-GR", "Provincie Groningen"),
            ("NL-LI", "Provincie Limburg"),
            ("NL-NB", "Provincie Noord-Brabant"),
            ("NL-NH", "Provincie Noord-Holland"),
            ("NL-OV", "Provincie Overijssel"),
            ("NL-UT", "Provincie Utrecht"),
            ("NL-ZE", "Provincie Zeeland"),
            ("NL-ZH", "Provincie Zuid-Holland"),
        ],
    ),
    (
        "US",
        &[
            ("US-AL", "Alabama"),
            ("US-AK", "Alaska"),
            ("US-AZ", "Arizona"),
            ("US-AR", "Arkansas"),
            ("US-CA", "California"),
            ("US-CO", "Colorado"),
            ("US-CT", "Connecticut"),
            ("US-DE", "Delaware"),
            ("US-FL", "Florida"),
            ("US-GA", "Georgia"),
            ("US-HI", "Hawaii"),
            ("US-ID", "Idaho"),
            ("US-IL", "Illinois"),
            ("US-IN", "Indiana"),
            ("US-IA", "Iowa"),
            ("US-KS", "Kansas"),
            ("US-KY", "Kentucky"),
            ("US-LA", "Louisiana"),
            ("US-ME", "Maine"),
            ("US-MD", "Maryland"),
            ("US-MA", "Massachusetts"),
            ("US-MI", "Michigan"),
            ("US-MN", "Minnesota"),
            ("US-MS", "Mississippi"),
            ("US-MO", "Missouri"),
            ("US-MT", "Montana"),
            ("US-NE", "Nebraska"),
            ("US-NV", "Nevada"),
            ("US-NH", "New Hampshire"),
            ("US-NJ", "New Jersey"),
            ("US-NM", "New Mexico"),
            ("US-NY", "New York"),
            ("US-NC", "North Carolina"),
            ("US-ND", "North Dakota"),
            ("US-OH", "Ohio"),
            ("US-OK", "Oklahoma"),
            ("US-OR", "Oregon"),
            ("US-PA", "Pennsylvania"),
            ("US-RI", "Rhode Island"),
            ("US-SC", "South Carolina"),
            ("US-SD", "South Dakota"),
            ("US-TN", "Tennessee"),
            ("US-TX", "Texas"),
            ("US-UT", "Utah"),
            ("US-VT", "Vermont"),
            ("US-VA", "Virginia"),
            ("US-WA", "Washington"),
            ("US-WV", "West Virginia"),
            ("US-WI", "Wisconsin"),
            ("US-WY", "Wyoming"),
            ("US-DC", "District of Columbia"),
        ],
    ),
    (
        "IT",
        &[
            ("IT-21", "Piemonte"),
            ("IT-23", "Regione Autonoma Valle d'Aosta"),
            ("IT-25", "Lombardia"),
            ("IT-32", "Trentino-Alto Adige"),
            ("IT-34", "Veneto"),
            ("IT-36", "Friuli Venezia Giulia"),
            ("IT-42", "Liguria"),
            ("IT-45", "Emilia-Romagna"),
            ("IT-52", "Toscana"),
            ("IT-55", "Umbria"),
            ("IT-57", "Marche"),
            ("IT-62", "Lazio"),
            ("IT-65", "Abruzzo"),
            ("IT-67", "Molise"),
            ("IT-72", "Campania"),
            ("IT-75", "Puglia"),
            ("IT-77", "Basilicata"),
            ("IT-78", "Calabria"),
            ("IT-82", "Sicilia"),
            ("IT-88", "Sardegna"),
        ],
    ),
    (
        "FR",
        &[
            ("FR-01", "Ain"),
            ("FR-02", "Aisne"),
            ("FR-03", "Allier"),
            ("FR-04", "Alpes-de-Haute-Provence"),
            ("FR-05", "Hautes-Alpes"),
            ("FR-06", "Alpes-Maritimes"),
            ("FR-07", "Ardèche"),
            ("FR-08", "Ardennes"),
            ("FR-09", "Ariège"),
            ("FR-10", "Aube"),
            ("FR-11", "Aude"),
            ("FR-12", "Aveyron"),
            ("FR-13", "Bouches-du-Rhône"),
            ("FR-14", "Calvados"),
            ("FR-15", "Cantal"),
            ("FR-16", "Charente"),
            ("FR-17", "Charente-Maritime"),
            ("FR-18", "Cher"),
            ("FR-19", "Corrèze"),
            ("FR-21", "Côte-d'Or"),
            ("FR-22", "Côtes-d'Armor"),
            ("FR-23", "Creuse"),
            ("FR-24", "Dordogne"),
            ("FR-25", "Doubs"),
            ("FR-26", "Drôme"),
            ("FR-27", "Eure"),
            ("FR-28", "Eure-et-Loir"),
            ("FR-29", "Finistère"),
            ("FR-2A", "Corse-du-Sud"),
            ("FR-2B", "Haute-Corse"),
            ("FR-30", "Gard"),
            ("FR-31", "Haute-Garonne"),
            ("FR-32", "Gers"),
            ("FR-33", "Gironde"),
            ("FR-34", "Hérault"),
            ("FR-35", "Ille-et-Vilaine"),
            ("FR-36", "Indre"),
            ("FR-37", "Indre-et-Loire"),
            ("FR-38", "Isère"),
            ("FR-39", "Jura"),
            ("FR-40", "Landes"),
            ("FR-41", "Loir-et-Cher"),
            ("FR-42", "Loire"),
            ("FR-43", "Haute-Loire"),
            ("FR-44", "Loire-Atlantique"),
            ("FR-45", "Loiret"),
            ("FR-46", "Lot"),
            ("FR-47", "Lot-et-Garonne"),
            ("FR-48", "Lozère"),
            ("FR-49", "Maine-et-Loire"),
            ("FR-50", "Manche"),
            ("FR-51", "Marne"),
            ("FR-52", "Haute-Marne"),
            ("FR-53", "Mayenne"),
            ("FR-54", "Meurthe-et-Moselle"),
            ("FR-55", "Meuse"),
            ("FR-56", "Morbihan"),
            ("FR-57", "Moselle"),
            ("FR-58", "Nièvre"),
            ("FR-59", "Nord"),
            ("FR-60", "Oise"),
            ("FR-61", "Orne"),
            ("FR-62", "Pas-de-Calais"),
            ("FR-63", "Puy-de-Dôme"),
            ("FR-64", "Pyrénées-Atlantiques"),
            ("FR-65", "Hautes-Pyrénées"),
            ("FR-66", "Pyrénées-Orientales"),
            ("FR-69", "Rhône"),
            ("FR-69M", "Métropole de Lyon"),
            ("FR-6AE", "Alsace"),
            ("FR-70", "Haute-Saône"),
            ("FR-71", "Saône-et-Loire"),
            ("FR-72", "Sarthe"),
            ("FR-73", "Savoie"),
            ("FR-74", "Haute-Savoie"),
            ("FR-75C", "Paris"),
            ("FR-76", "Seine-Maritime"),
            ("FR-77", "Seine-et-Marne"),
            ("FR-78", "Yvelines"),
            ("FR-79", "Deux-Sèvres"),
            ("FR-80", "Somme"),
            ("FR-81", "Tarn"),
            ("FR-82", "Tarn-et-Garonne"),
            ("FR-83", "Var"),
            ("FR-84", "Vaucluse"),
            ("FR-85", "Vendée"),
            ("FR-86", "Vienne"),
            ("FR-87", "Haute-Vienne"),
            ("FR-88", "Vosges"),
            ("FR-89", "Yonne"),
            ("FR-90", "Territoire de Belfort"),
            ("FR-91", "Essonne"),
            ("FR-92", "Hauts-de-Seine"),
            ("FR-93", "Seine-Saint-Denis"),
            ("FR-94", "Val-de-Marne"),
            ("FR-95", "Val-d'Oise"),
        ],
    ),
    (
        "LU",
        &[
            ("LU-CA", "Capellen"),
            ("LU-CL", "Clervaux"),
            ("LU-DI", "Diekirch"),
            ("LU-EC", "Canton d'Echternach"),
            ("LU-ES", "Canton d'Esch-sur-Alzette"),
            ("LU-GR", "Grevenmacher"),
            ("LU-LU", "Luxembourg"),
            ("LU-ME", "Mersch"),
            ("LU-RD", "Redange"),
            ("LU-RM", "Remich"),
            ("LU-VD", "Vianden"),
            ("LU-WI", "Wiltz"),
        ],
    ),
    (
        "AU",
        &[
            ("AU-ACT", "Australian Capital Territory"),
            ("AU-NSW", "New South Wales"),
            ("AU-NT", "Northern Territory"),
            ("AU-QLD", "Queensland"),
            ("AU-SA", "South Australia"),
            ("AU-TAS", "Tasmania"),
            ("AU-VIC", "Victoria"),
            ("AU-WA", "Western Australia"),
            ("Jervis Bay Territory", "Jervis Bay Territory"),
        ],
    ),
    (
        "NO",
        &[
            ("NO-03", "Oslo"),
            ("NO-11", "Rogaland"),
            ("NO-15", "Møre og Romsdal"),
            ("NO-18", "Nordland"),
            ("NO-21", "Svalbard"),
            ("NO-31", "Østfold"),
            ("NO-32", "Akershus"),
            ("NO-33", "Buskerud"),
            ("NO-34", "Innlandet"),
            ("NO-39", "Vestfold"),
            ("NO-40", "Telemark"),
            ("NO-42", "Agder"),
            ("NO-46", "Vestland"),
            ("NO-50", "Trøndelag"),
            ("NO-55", "Troms"),
            ("NO-56", "Finnmark"),
        ],
    ),
    (
        "SE",
        &[
            ("SE-AB", "Stockholm"),
            ("SE-AC", "Vasterbotten"),
            ("SE-BD", "Norrbotten"),
            ("SE-C", "Uppsala"),
            ("SE-D", "Sodermanland"),
            ("SE-E", "Ostergotland"),
            ("SE-F", "Jonkoping"),
            ("SE-G", "Kronoberg"),
            ("SE-H", "Kalmar"),
            ("SE-I", "Gotland"),
            ("SE-K", "Blekinge"),
            ("SE-M", "Skane"),
            ("SE-N", "Halland"),
            ("SE-O", "Vastra Gotaland"),
            ("SE-S", "Varmland"),
            ("SE-T", "Orebro"),
            ("SE-U", "Vastmanland"),
            ("SE-W", "Dalarna"),
            ("SE-X", "Gavleborg"),
            ("SE-Y", "Vasternorrland"),
            ("SE-Z", "Jamtland"),
        ],
    ),
    (
        "HR",
        &[
            ("HR-01", "Zagreb County"),
            ("HR-02", "Krapina-Zagorje"),
            ("HR-03", "Sisak-Moslavina"),
            ("HR-04", "Karlovac"),
            ("HR-05", "Varazdin"),
            ("HR-06", "Koprivinica-Krizevci"),
            ("HR-07", "Bjelovar-Bilogora"),
            ("HR-08", "Primorsko-Goranska Zupanija"),
            ("HR-09", "Lika-Senj"),
            ("HR-10", "Virovitica-Podravina"),
            ("HR-11", "Pozega-Slavonia"),
            ("HR-12", "Brod-Posavina"),
            ("HR-13", "Zadar"),
            ("HR-14", "Osjecko-Baranjska Zupanija"),
            ("HR-15", "Sibenik-Knin"),
            ("HR-16", "Vukovar-Srijem"),
            ("HR-17", "Split-Dalmatia"),
            ("HR-18", "Istria"),
            ("HR-19", "Dubrovacko-Neretvanska Zupanija"),
            ("HR-20", "Medimurje"),
            ("HR-21", "Grad Zagreb"),
        ],
    ),
    (
        "EE",
        &[
            ("EE-37", "Harjumaa"),
            ("Hiiumaa vald", "Harjumaa"),
            ("EE-39", "Hiiumaa"),
            ("EE-44", "Ida-Virumaa"),
            ("EE-50", "Jogevamaa"),
            ("EE-52", "Jarvamaa"),
            ("EE-57", "Laanemaa"),
            ("EE-59", "Laane-Virumaa"),
            ("EE-64", "Polvamaa"),
            ("EE-68", "Parnumaa"),
            ("EE-70", "Raplamaa"),
            ("EE-74", "Saaremaa"),
            ("EE-79", "Tartumaa"),
            ("EE-81", "Valgamaa"),
            ("EE-84", "Viljandimaa"),
            ("EE-87", "Vorumaa"),
        ],
    ),
    (
        "MX",
        &[
            ("MX-AGU", "Aguascalientes"),
            ("MX-BCN", "Baja California"),
            ("MX-BCS", "Baja California Sur"),
            ("MX-CAM", "Campeche"),
            ("MX-CHH", "Chihuahua"),
            ("MX-CHP", "Chiapas"),
            ("MX-CMX", "Mexico City"),
            ("MX-COA", "Coahuila de Zaragoza"),
            ("MX-COL", "Colima"),
            ("MX-DUR", "Durango"),
            ("MX-GRO", "Guerrero"),
            ("MX-GUA", "Guanajuato"),
            ("MX-HID", "Hidalgo"),
            ("MX-JAL", "Jalisco"),
            ("MX-MEX", "Mexico"),
            ("MX-MIC", "Michoacan de Ocampo"),
            ("MX-MOR", "Morelos"),
            ("MX-NAY", "Nayarit"),
            ("MX-NLE", "Nuevo Leon"),
            ("MX-OAX", "Oaxaca"),
            ("MX-PUE", "Puebla"),
            ("MX-QUE", "Queretaro"),
            ("MX-ROO", "Quintana Roo"),
            ("MX-SIN", "Sinaloa"),
            ("MX-SLP", "San Luis Potosi"),
            ("MX-SON", "Sonora"),
            ("MX-TAB", "Tabasco"),
            ("MX-TAM", "Tamaulipas"),
            ("MX-TLA", "Tlaxcala"),
            ("MX-VER", "Veracruz-Llave"),
            ("MX-YUC", "Yucatan"),
            ("MX-ZAC", "Zacatecas"),
        ],
    ),
    ("PR", &[("US-PR", "Puerto Rico")]),
    (
        "DO",
        &[
            ("DO-01", "Distrito Nacional"),
            ("DO-13", "Provincia de La Vega"),
            ("DO-25", "Provincia de Santiago"),
            ("DO-32", "Provincia de Santo Domingo"),
        ],
    ),
    ("CW", &[("NL-CW", "Curaçao")]),
    (
        "PA",
        &[
            ("PA-1", "Bocas del Toro"),
            ("PA-10", "Panamá Oeste"),
            ("PA-2", "Cocle"),
            ("PA-3", "Colon"),
            ("PA-4", "Chiriqui"),
            ("PA-5", "Darien"),
            ("PA-6", "Herrera"),
            ("PA-7", "Los Santos"),
            ("PA-8", "Panama"),
            ("PA-9", "Veraguas"),
            ("PA-NB", "Ngobe-Bugle"),
            ("PA-NT", "Naso Tjër Di"),
        ],
    ),
    (
        "CO",
        &[
            ("CO-AMA", "Amazonas"),
            ("CO-ANT", "Antioquia"),
            ("CO-ARA", "Arauca"),
            ("CO-ATL", "Atlantico"),
            ("CO-BOL", "Bolivar"),
            ("CO-BOY", "Boyaca"),
            ("CO-CAL", "Caldas"),
            ("CO-CAQ", "Caqueta"),
            ("CO-CAS", "Casanare"),
            ("CO-CAU", "Cauca"),
            ("CO-CES", "Cesar"),
            ("CO-CHO", "Choco"),
            ("CO-COR", "Cordoba"),
            ("CO-CUN", "Cundinamarca"),
            ("CO-DC", "Distrito Capital de Bogota"),
            ("CO-GUA", "Guainia"),
            ("CO-GUV", "Guaviare"),
            ("CO-HUI", "Huila"),
            ("CO-LAG", "La Guajira"),
            ("CO-MAG", "Magdalena"),
            ("CO-MET", "Meta"),
            ("CO-NAR", "Narino"),
            ("CO-NSA", "Norte de Santander"),
            ("CO-PUT", "Putumayo"),
            ("CO-QUI", "Quindio"),
            ("CO-RIS", "Risaralda"),
            ("CO-SAN", "Santander"),
            ("CO-SAP", "San Andrés"),
            ("CO-SUC", "Sucre"),
            ("CO-TOL", "Tolima"),
            ("CO-VAC", "Valle del Cauca"),
            ("CO-VAU", "Vaupes"),
            ("CO-VID", "Vichada"),
        ],
    ),
    (
        "EC",
        &[
            ("EC-A", "Azuay"),
            ("EC-B", "Bolivar"),
            ("EC-C", "Carchi"),
            ("EC-D", "Orellana"),
            ("EC-E", "Esmeraldas"),
            ("EC-F", "Canar"),
            ("EC-G", "Guayas"),
            ("EC-H", "Chimborazo"),
            ("EC-I", "Imbabura"),
            ("EC-L", "Loja"),
            ("EC-M", "Manabi"),
            ("EC-N", "Napo"),
            ("EC-O", "El Oro"),
            ("EC-P", "Pichincha"),
            ("EC-R", "Los Rios"),
            ("EC-S", "Morona Santiago"),
            ("EC-SD", "Santo Domingo de los Tsachilas"),
            ("EC-SE", "Santa Elena"),
            ("EC-T", "Tungurahua"),
            ("EC-U", "Sucumbios"),
            ("EC-X", "Cotopaxi"),
            ("EC-Y", "Pastaza"),
            ("EC-Z", "Zamora Chinchipe"),
        ],
    ),
    (
        "PE",
        &[
            ("PE-AMA", "Amazonas"),
            ("PE-ANC", "Ancash"),
            ("PE-APU", "Region de Apurimac"),
            ("PE-ARE", "Arequipa"),
            ("PE-AYA", "Ayacucho"),
            ("PE-CAJ", "Cajamarca"),
            ("PE-CAL", "Callao"),
            ("PE-CUS", "Cusco"),
            ("PE-HUC", "Region de Huanuco"),
            ("PE-HUV", "Huancavelica"),
            ("PE-ICA", "Ica"),
            ("PE-JUN", "Junin"),
            ("PE-LAL", "La Libertad"),
            ("PE-LAM", "Lambayeque"),
            ("PE-LIM", "Lima"),
            ("PE-LOR", "Loreto"),
            ("PE-MDD", "Madre de Dios"),
            ("PE-MOQ", "Departamento de Moquegua"),
            ("PE-PAS", "Pasco"),
            ("PE-PIU", "Piura"),
            ("PE-PUN", "Puno"),
            ("PE-SAM", "Region de San Martin"),
            ("PE-TAC", "Tacna"),
            ("PE-TUM", "Tumbes"),
            ("PE-UCA", "Ucayali"),
        ],
    ),
    (
        "BO",
        &[
            ("BO-C", "Departamento de Cochabamba"),
            ("BO-H", "Departamento de Chuquisaca"),
            ("BO-L", "Departamento de La Paz"),
            ("BO-O", "Departamento de Oruro"),
            ("BO-P", "Departamento de Potosi"),
            ("BO-S", "Departamento de Santa Cruz"),
            ("BO-T", "Departamento de Tarija"),
        ],
    ),
    (
        "CL",
        &[
            ("CL-AI", "Region Aysen"),
            ("CL-AN", "Antofagasta"),
            ("CL-AP", "Arica and Parinacota"),
            ("CL-AR", "Araucania"),
            ("CL-AT", "Atacama"),
            ("CL-BI", "Biobio"),
            ("CL-CO", "Coquimbo"),
            ("CL-LI", "O'Higgins"),
            ("CL-LL", "Lagos"),
            ("CL-LR", "Rios"),
            ("CL-MA", "Magellan"),
            ("CL-ML", "Maule"),
            ("CL-NB", "Nuble"),
            ("CL-RM", "Region Metropolitana"),
            ("CL-TA", "Tarapaca"),
            ("CL-VS", "Valparaiso"),
        ],
    ),
    (
        "AR",
        &[
            ("AR-A", "Salta"),
            ("AR-B", "Buenos Aires"),
            ("AR-C", "Buenos Aires city"),
            ("AR-D", "San Luis"),
            ("AR-E", "Entre Rios"),
            ("AR-F", "La Rioja"),
            ("AR-G", "Santiago del Estero"),
            ("AR-H", "Chaco"),
            ("AR-J", "San Juan"),
            ("AR-K", "Catamarca"),
            ("AR-L", "La Pampa"),
            ("AR-M", "Mendoza"),
            ("AR-N", "Misiones"),
            ("AR-P", "Formosa"),
            ("AR-Q", "Neuquen"),
            ("AR-R", "Rio Negro"),
            ("AR-S", "Santa Fe"),
            ("AR-T", "Tucuman"),
            ("AR-U", "Chubut"),
            ("AR-V", "Tierra del Fuego"),
            ("AR-W", "Corrientes"),
            ("AR-X", "Cordoba"),
            ("AR-Y", "Jujuy"),
            ("AR-Z", "Santa Cruz"),
        ],
    ),
    (
        "BR",
        &[
            ("BR-AC", "Acre"),
            ("BR-AL", "Alagoas"),
            ("BR-AM", "Amazonas"),
            ("BR-AP", "Amapa"),
            ("BR-BA", "Bahia"),
            ("BR-CE", "Ceara"),
            ("BR-DF", "Federal District"),
            ("BR-ES", "Espirito Santo"),
            ("BR-GO", "Goias"),
            ("BR-MA", "Maranhao"),
            ("BR-MG", "Minas Gerais"),
            ("BR-MS", "Mato Grosso do Sul"),
            ("BR-MT", "Mato Grosso"),
            ("BR-PA", "Para"),
            ("BR-PB", "Paraiba"),
            ("BR-PE", "Pernambuco"),
            ("BR-PI", "Piaui"),
            ("BR-PR", "Parana"),
            ("BR-RJ", "Rio de Janeiro"),
            ("BR-RN", "Rio Grande do Norte"),
            ("BR-RO", "Rondonia"),
            ("BR-RR", "Roraima"),
            ("BR-RS", "Rio Grande do Sul"),
            ("BR-SC", "Santa Catarina"),
            ("BR-SE", "Sergipe"),
            ("BR-SP", "Sao Paulo"),
            ("BR-TO", "Tocantins"),
        ],
    ),
    (
        "UY",
        &[
            ("UY-AR", "Departamento de Artigas"),
            ("UY-CA", "Departamento de Canelones"),
            ("UY-CL", "Departamento de Cerro Largo"),
            ("UY-CO", "Departamento de Colonia"),
            ("UY-DU", "Departamento de Durazno"),
            ("UY-FD", "Departamento de Florida"),
            ("UY-FS", "Departamento de Flores"),
            ("UY-LA", "Departamento de Lavalleja"),
            ("UY-MA", "Departamento de Maldonado"),
            ("UY-MO", "Departamento de Montevideo"),
            ("UY-PA", "Departamento de Paysandu"),
            ("UY-RN", "Departamento de Rio Negro"),
            ("UY-RO", "Departamento de Rocha"),
            ("UY-RV", "Departamento de Rivera"),
            ("UY-SA", "Departamento de Salto"),
            ("UY-SJ", "Departamento de San Jose"),
            ("UY-SO", "Departamento de Soriano"),
            ("UY-TA", "Departamento de Tacuarembo"),
            ("UY-TT", "Departamento de Treinta y Tres"),
        ],
    ),
    (
        "GT",
        &[
            ("GT-01", "Departamento de Guatemala"),
            ("GT-02", "Departamento de El Progreso"),
            ("GT-03", "Departamento de Sacatepequez"),
            ("GT-04", "Departamento de Chimaltenango"),
            ("GT-05", "Departamento de Escuintla"),
            ("GT-06", "Departamento de Santa Rosa"),
            ("GT-07", "Departamento de Solola"),
            ("GT-08", "Departamento de Totonicapan"),
            ("GT-09", "Departamento de Quetzaltenango"),
            ("GT-10", "Departamento de Suchitepequez"),
            ("GT-11", "Departamento de Retalhuleu"),
            ("GT-12", "Departamento de San Marcos"),
            ("GT-13", "Departamento de Huehuetenango"),
            ("GT-14", "Departamento del Quiche"),
            ("GT-15", "Departamento de Baja Verapaz"),
            ("GT-16", "Departamento de Alta Verapaz"),
            ("GT-17", "Departamento del Peten"),
            ("GT-18", "Departamento de Izabal"),
            ("GT-19", "Departamento de Zacapa"),
            ("GT-20", "Departamento de Chiquimula"),
            ("GT-21", "Departamento de Jalapa"),
            ("GT-22", "Departamento de Jutiapa"),
        ],
    ),
    (
        "ID",
        &[
            ("ID-AC", "Aceh"),
            ("ID-BA", "Bali"),
            ("ID-BB", "Bangka Belitung"),
            ("ID-BE", "Bengkulu"),
            ("ID-BT", "Banten"),
            ("ID-GO", "Gorontalo"),
            ("ID-JA", "Jambi"),
            ("ID-JB", "West Java"),
            ("ID-JI", "East Java"),
            ("ID-JK", "Jakarta"),
            ("ID-JT", "Central Java"),
            ("ID-KB", "West Kalimantan"),
            ("ID-KI", "East Kalimantan"),
            ("ID-KR", "Riau Islands"),
            ("ID-KS", "South Kalimantan"),
            ("ID-KT", "Central Kalimantan"),
            ("ID-KU", "North Kalimantan"),
            ("ID-LA", "Lampung"),
            ("ID-MU", "North Maluku"),
            ("ID-NB", "West Nusa Tenggara"),
            ("ID-NT", "East Nusa Tenggara"),
            ("ID-RI", "Riau"),
            ("ID-SA", "North Sulawesi"),
            ("ID-SB", "West Sumatra"),
            ("ID-SG", "Southeast Sulawesi"),
            ("ID-SN", "South Sulawesi"),
            ("ID-SR", "West Sulawesi"),
            ("ID-SS", "South Sumatra"),
            ("ID-ST", "Central Sulawesi"),
            ("ID-SU", "North Sumatra"),
            ("ID-YO", "Yogyakarta"),
        ],
    ),
    (
        "CA",
        &[
            ("CA-AB", "Alberta"),
            ("CA-BC", "British Columbia"),
            ("CA-MB", "Manitoba"),
            ("CA-NB", "New Brunswick"),
            ("CA-NL", "Newfoundland and Labrador"),
            ("CA-NS", "Nova Scotia"),
            ("CA-NT", "Northwest Territories"),
            ("CA-ON", "Ontario"),
            ("CA-PE", "Prince Edward Island"),
            ("CA-QC", "Quebec"),
            ("CA-SK", "Saskatchewan"),
            ("CA-YT", "Yukon"),
            ("CA-NU", "Nunavut"),
        ],
    ),
    (
        "GR",
        &[
            ("GR-A", "Eastern Macedonia and Thrace"),
            ("GR-B", "Central Macedonia"),
            ("GR-C", "Western Macedonia"),
            ("GR-D", "Epirus"),
            ("GR-E", "Thessaly"),
            ("GR-F", "Ionian Islands"),
            ("GR-G", "Western Greece"),
            ("GR-H", "Central Greece"),
            ("GR-I", "Attica"),
            ("GR-J", "Peloponnese"),
            ("GR-K", "North Aegean"),
            ("GR-L", "South Aegean"),
            ("GR-M", "Crete"),
        ],
    ),
    (
        "HU",
        &[
            ("HU-BA", "Baranya"),
            ("HU-BE", "Bekes"),
            ("HU-BK", "Bacs-Kiskun"),
            ("HU-BU", "Budapest"),
            ("HU-BZ", "Borsod-Abauj-Zemplen"),
            ("HU-CS", "Csongrad-Csanad"),
            ("HU-FE", "Fejer"),
            ("HU-GS", "Gyor-Moson-Sopron"),
            ("HU-HB", "Hajdu-Bihar"),
            ("HU-HE", "Heves"),
            ("HU-JN", "Jasz-Nagykun-Szolnok"),
            ("HU-KE", "Komarom-Esztergom"),
            ("HU-NO", "Nograd"),
            ("HU-PE", "Pest"),
            ("HU-SO", "Somogy"),
            ("HU-SZ", "Szabolcs-Szatmar-Bereg"),
            ("HU-TO", "Tolna"),
            ("HU-VA", "Vas"),
            ("HU-VE", "Veszprem"),
            ("HU-ZA", "Zala"),
            ("Great Plain and North", "Great Plain and North"),
            ("Central Hungary", "Central Hungary"),
            ("Transdanubia", "Transdanubia"),
        ],
    ),
    (
        "IS",
        &[
            ("IS-1", "Hofudborgarsvaedi"),
            ("IS-2", "Sudurnes"),
            ("IS-3", "Vesturland"),
            ("IS-4", "Vestfirdir"),
            ("IS-5", "Nordurland Vestra"),
            ("IS-6", "Nordurland Eystra"),
            ("IS-7", "Austurland"),
            ("IS-8", "Sudurland"),
        ],
    ),
    (
        "FI",
        &[
            ("FI-02", "South Karelia Region"),
            ("FI-03", "South Ostrobothnia"),
            ("FI-04", "Southern Savonia"),
            ("FI-05", "Kainuu"),
            ("FI-06", "Kanta-Hame"),
            ("FI-07", "Keski-Pohjanmaa"),
            ("FI-08", "Mellersta Finland"),
            ("FI-09", "Kymenlaakso"),
            ("FI-11", "Pirkanmaa"),
            ("FI-12", "Pohjanmaa"),
            ("FI-13", "Pohjois-Karjala"),
            ("FI-14", "Pohjois-Pohjanmaa"),
            ("FI-15", "Pohjois-Savo"),
            ("FI-16", "Paijat-Hame Region"),
            ("FI-17", "Satakunta"),
            ("FI-18", "Uusimaa"),
            ("FI-19", "Varsinais-Suomi"),
            ("FI-10", "Lapland"),
        ],
    ),
    (
        "LV",
        &[
            ("LV-002", "Aizkraukles novads"),
            ("LV-007", "Aluksnes Novads"),
            ("LV-011", "Adazu Novads"),
            ("LV-015", "Balvu Novads"),
            ("LV-016", "Bauskas Novads"),
            ("LV-022", "Cesu Novads"),
            ("LV-026", "Dobeles novads"),
            ("LV-033", "Gulbenes novads"),
            ("LV-041", "Jelgavas novads"),
            ("LV-042", "Jekabpils Municipality"),
            ("LV-047", "Kraslavas novads"),
            ("LV-050", "Kuldigas novads"),
            ("LV-052", "Kekavas Novads"),
            ("LV-054", "Limbazu novads"),
            ("LV-056", "Livanu Novads"),
            ("LV-058", "Ludzas novads"),
            ("LV-059", "Madona Municipality"),
            ("LV-062", "Marupes Novads"),
            ("LV-067", "Ogres novads"),
            ("LV-068", "Olaines Novads"),
            ("LV-073", "Preili Municipality"),
            ("LV-077", "Rezeknes Novads"),
            ("LV-080", "Ropazu Novads"),
            ("LV-087", "Salaspils Novads"),
            ("LV-088", "Saldus Municipality"),
            ("LV-089", "Saulkrastu Novads"),
            ("LV-091", "Siguldas Novads"),
            ("LV-094", "Smiltenes Novads"),
            ("LV-097", "Talsi Municipality"),
            ("LV-099", "Tukuma novads"),
            ("LV-101", "Valka Municipality"),
            ("LV-102", "Varaklanu Novads"),
            ("LV-106", "Ventspils Municipality"),
            ("LV-111", "Augsdaugava Municipality"),
            ("LV-112", "South Kurzeme Municipality"),
            ("LV-113", "Valmiera"),
            ("LV-DGV", "Daugavpils"),
            ("LV-JEL", "Jelgava"),
            ("LV-JUR", "Jurmala"),
            ("LV-LPX", "Liepaja"),
            ("LV-REZ", "Rezekne"),
            ("LV-RIX", "Riga"),
            ("LV-VEN", "Ventspils"),
        ],
    ),
    (
        "LT",
        &[
            ("LT-AL", "Alytus County"),
            ("LT-KL", "Klaipeda County"),
            ("LT-KU", "Kaunas County"),
            ("LT-MR", "Marijampole County"),
            ("LT-PN", "Panevezys"),
            ("LT-SA", "Siauliai County"),
            ("LT-TA", "Taurage County"),
            ("LT-TE", "Telsių apskritis"),
            ("LT-UT", "Utena County"),
            ("LT-VL", "Vilnius County"),
        ],
    ),
    (
        "PL",
        &[
            ("PL-02", "Lower Silesian Voivodeship"),
            ("PL-04", "Kuyavian-Pomeranian Voivodeship"),
            ("PL-06", "Lublin Voivodeship"),
            ("PL-08", "Lubusz Voivodeship"),
            ("PL-10", "Wojewodztwo Lodzkie"),
            ("PL-12", "Lesser Poland Voivodeship"),
            ("PL-14", "Masovian Voivodeship"),
            ("PL-16", "Opole Voivodeship"),
            ("PL-18", "Podkarpackie Voivodeship"),
            ("PL-20", "Podlaskie Voivodeship"),
            ("PL-22", "Pomeranian Voivodeship"),
            ("PL-24", "Silesian Voivodeship"),
            ("PL-26", "Wojewodztwo Swietokrzyskie"),
            ("PL-28", "Warmian-Masurian Voivodeship"),
            ("PL-30", "Greater Poland Voivodeship"),
            ("PL-32", "West Pomeranian Voivodeship"),
        ],
    ),
    (
        "SZ",
        &[
            ("SZ-HH", "Hhohho"),
            ("SZ-LU", "Lubombo"),
            ("SZ-MA", "Manzini"),
            ("SZ-SH", "Shiselweni"),
        ],
    ),
    (
        "AT",
        &[
            ("AT-1", "Burgenland"),
            ("AT-2", "Karnten"),
            ("AT-3", "Niederosterreich"),
            ("AT-4", "Oberosterreich"),
            ("AT-5", "Salzburg"),
            ("AT-6", "Steiermark"),
            ("AT-7", "Tirol"),
            ("AT-8", "Vorarlberg"),
            ("AT-9", "Vienna"),
        ],
    ),
    (
        "ES",
        &[
            ("ES-AN", "Andalusia"),
            ("ES-AR", "Aragon"),
            ("ES-AS", "Principality of Asturias"),
            ("ES-CB", "Cantabria"),
            ("ES-CE", "Ceuta"),
            ("ES-CL", "Castilla y Leon"),
            ("ES-CM", "Castilla-La Mancha"),
            ("ES-CN", "Canarias"),
            ("ES-CT", "Catalunya"),
            ("ES-EX", "Extremadura"),
            ("ES-GA", "Galicia"),
            ("ES-IB", "Illes Balears"),
            ("ES-MC", "Region de Murcia"),
            ("ES-MD", "Comunidad de Madrid"),
            ("ES-ML", "Melilla"),
            ("ES-NC", "Navarra"),
            ("ES-PV", "Euskal Autonomia Erkidegoa"),
            ("ES-RI", "La Rioja"),
            ("ES-VC", "Comunitat Valenciana"),
        ],
    ),
    (
        "DE",
        &[
            ("DE-BB", "Brandenburg"),
            ("DE-BE", "Land Berlin"),
            ("DE-BW", "Baden-Wurttemberg"),
            ("DE-BY", "Bavaria"),
            ("DE-HB", "Bremen"),
            ("DE-HE", "Hessen"),
            ("DE-HH", "Free and Hanseatic City of Hamburg"),
            ("DE-MV", "Mecklenburg-Western Pomerania"),
            ("DE-NI", "Lower Saxony"),
            ("DE-NW", "Nordrhein-Westfalen"),
            ("DE-RP", "Rheinland-Pfalz"),
            ("DE-SH", "Schleswig-Holstein"),
            ("DE-SL", "Saarland"),
            ("DE-SN", "Saxony"),
            ("DE-ST", "Saxony-Anhalt"),
            ("DE-TH", "Thuringia"),
        ],
    ),
    (
        "CZ",
        &[
            ("CZ-10", "Prague"),
            ("CZ-20", "Stredocesky kraj"),
            ("CZ-31", "Jihocesky kraj"),
            ("CZ-32", "Plzensky kraj"),
            ("CZ-41", "Karlovarsky kraj"),
            ("CZ-42", "Ustecky kraj"),
            ("CZ-51", "Liberecky kraj"),
            ("CZ-52", "Kralovehradecky kraj"),
            ("CZ-53", "Pardubicky kraj"),
            ("CZ-63", "Kraj Vysocina"),
            ("CZ-64", "Jihomoravsky kraj"),
            ("CZ-71", "Olomoucky kraj"),
            ("CZ-72", "Zlinsky kraj"),
            ("CZ-80", "Moravskoslezsky kraj"),
        ],
    ),
    (
        "SK",
        &[
            ("SK-BC", "Banska Bystrica"),
            ("SK-BL", "Bratislava"),
            ("SK-KI", "Kosice"),
            ("SK-NI", "Nitra"),
            ("SK-PV", "Presov"),
            ("SK-TA", "Trnava"),
            ("SK-TC", "Trencin"),
            ("SK-ZI", "Zilina"),
        ],
    ),
    (
        "BE",
        &[
            ("BE-VAN", "Antwerpen"),
            ("BE-VBR", "Vlaams-Brabant"),
            ("BE-VLI", "Limburg"),
            ("BE-VOV", "Oost-Vlaanderen"),
            ("BE-VWV", "West-Vlaanderen"),
            ("BE-WBR", "Brabant wallon"),
            ("BE-WHT", "Hainaut"),
            ("BE-WLG", "Liege"),
            ("BE-WLX", "Luxembourg"),
            ("BE-WNA", "Namurc"),
            ("BE-BRU", "Brussels"),
        ],
    ),
    (
        "PT",
        &[
            ("PT-01", "Distrito de Aveiro"),
            ("PT-02", "Distrito de Beja"),
            ("PT-03", "Distrito de Braga"),
            ("PT-04", "Distrito de Braganca"),
            ("PT-05", "Distrito de Castelo Branco"),
            ("PT-06", "Distrito de Coimbra"),
            ("PT-07", "Distrito de Evora"),
            ("PT-08", "Distrito de Faro"),
            ("PT-09", "Distrito da Guarda"),
            ("PT-10", "Distrito de Leiria"),
            ("PT-11", "Distrito de Lisboa"),
            ("PT-12", "Distrito de Portalegre"),
            ("PT-13", "Distrito do Porto"),
            ("PT-14", "Distrito de Santarem"),
            ("PT-15", "Distrito de Setubal"),
            ("PT-16", "Distrito de Viana do Castelo"),
            ("PT-17", "Distrito de Vila Real"),
            ("PT-18", "Distrito de Viseu"),
            ("PT-20", "Azores"),
            ("PT-30", "Madeira"),
        ],
    ),
    (
        "RO",
        &[
            ("RO-AB", "Alba"),
            ("RO-AG", "Arges"),
            ("RO-AR", "Arad"),
            ("RO-B", " București"),
            ("RO-BC", "Bacau"),
            ("RO-BH", "Bihor"),
            ("RO-BN", "Bistriţa-Nasaud"),
            ("RO-BR", "Braila"),
            ("RO-BT", "Botosani"),
            ("RO-BV", "Brasov"),
            ("RO-BZ", "Buzau"),
            ("RO-CJ", "Cluj"),
            ("RO-CL", "Calarasi"),
            ("RO-CS", "Caras-Severin"),
            ("RO-CT", "Constanta"),
            ("RO-CV", "Covasna"),
            ("RO-DB", "Damboviţa"),
            ("RO-DJ", "Dolj"),
            ("RO-GJ", "Gorj"),
            ("RO-GL", "Galaţi"),
            ("RO-GR", "Giurgiu"),
            ("RO-HD", "Hunedoara"),
            ("RO-HR", "Harghita"),
            ("RO-IF", "Ilfov"),
            ("RO-IL", "Ialomiţa"),
            ("RO-IS", "Iasi"),
            ("RO-MH", "Mehedinţi"),
            ("RO-MM", "Maramures"),
            ("RO-MS", "Mures"),
            ("RO-NT", "Neamţ"),
            ("RO-OT", "Olt"),
            ("RO-PH", "Prahova"),
            ("RO-SB", "Sibiu"),
            ("RO-SJ", "Salaj"),
            ("RO-SM", "Satu Mare"),
            ("RO-SV", "Suceava"),
            ("RO-TL", "Tulcea"),
            ("RO-TM", "Timis"),
            ("RO-TR", "Teleorman"),
            ("RO-VL", "Valcea"),
            ("RO-VN", "Vrancea"),
            ("RO-VS", "Vaslui"),
        ],
    ),
    (
        "BG",
        &[
            ("BG-01", "Blagoevgrad"),
            ("BG-02", "Burgas"),
            ("BG-03", "Varna"),
            ("BG-04", "Oblast Veliko Tarnovo"),
            ("BG-05", "Oblast Vidin"),
            ("BG-06", "Oblast Vratsa"),
            ("BG-07", "Gabrovo"),
            ("BG-08", "Oblast Dobrich"),
            ("BG-09", "Oblast Kardzhali"),
            ("BG-10", "Oblast Kyustendil"),
            ("BG-11", "Lovech"),
            ("BG-12", "Oblast Montana"),
            ("BG-13", "Pazardzhik"),
            ("BG-14", "Pernik"),
            ("BG-15", "Oblast Pleven"),
            ("BG-16", "Plovdiv"),
            ("BG-17", "Oblast Razgrad"),
            ("BG-18", "Oblast Ruse"),
            ("BG-19", "Oblast Silistra"),
            ("BG-20", "Oblast Sliven"),
            ("BG-21", "Oblast Smolyan"),
            ("BG-22", "Sofia-Grad"),
            ("BG-23", "Sofia"),
            ("BG-24", "Oblast Stara Zagora"),
            ("BG-25", "Oblast Targovishte"),
            ("BG-26", "Haskovo"),
            ("BG-27", "Oblast Shumen"),
            ("BG-28", "Oblast Yambol"),
        ],
    ),
    (
        "MK",
        &[
            ("MK-101", "Veles"),
            ("MK-102", "Gradsko"),
            ("MK-103", "Demir Kapija"),
            ("MK-104", "Kavadarci"),
            ("MK-105", "Lozovo"),
            ("MK-106", "Negotino"),
            ("MK-107", "Rosoman"),
            ("MK-108", "Sveti Nikole"),
            ("MK-201", "Berovo"),
            ("MK-202", "Vinica"),
            ("MK-203", "Opstina Delcevo"),
            ("MK-205", "Karbinci"),
            ("MK-206", "Opstina Kocani"),
            ("MK-207", "Makedonska Kamenica"),
            ("MK-208", "Opstina Pehcevo"),
            ("MK-209", "Opstina Probistip"),
            ("MK-210", "Cesinovo-Oblesevo"),
            ("MK-211", "Opstina Stip"),
            ("MK-304", "Debarca"),
            ("MK-307", "Opstina Kicevo"),
            ("MK-310", "Ohrid"),
            ("MK-402", "Bosilovo"),
            ("MK-403", "Valandovo"),
            ("MK-404", "Vasilevo"),
            ("MK-405", "Gevgelija"),
            ("MK-406", "Opstina Dojran"),
            ("MK-408", "Novo Selo"),
            ("MK-409", "Opstina Radovis"),
            ("MK-410", "Strumica"),
            ("MK-501", "Bitola"),
            ("MK-506", "Mogila"),
            ("MK-508", "Prilep"),
            ("MK-509", "Resen"),
            ("MK-601", "Bogovinje"),
            ("MK-602", "Brvenica"),
            ("MK-603", "Opstina Vrapciste"),
            ("MK-604", "Gostivar"),
            ("MK-605", "Opstina Zelino"),
            ("MK-607", "Opstina Mavrovo i Rostusa"),
            ("MK-609", "Tetovo"),
            ("MK-701", "Kratovo"),
            ("MK-702", "Kriva Palanka"),
            ("MK-703", "Kumanovo"),
            ("MK-704", "Opstina Lipkovo"),
            ("MK-705", "Opstina Rankovce"),
            ("MK-706", "Opstina Staro Nagoricane"),
            ("MK-802", "Opstina Aracinovo"),
            ("MK-807", "Ilinden"),
            ("MK-810", "Petrovec"),
            ("MK-816", "Opstina Cucer-Sandevo"),
            ("MK-85", "Cair"),
        ],
    ),
    (
        "ME",
        &[
            ("ME-01", "Andrijevica"),
            ("ME-02", "Bar"),
            ("ME-03", "Berane"),
            ("ME-04", "Bijelo Polje"),
            ("ME-05", "Budva"),
            ("ME-06", "Cetinje"),
            ("ME-07", "Danilovgrad"),
            ("ME-08", "Herceg Novi"),
            ("ME-09", "Opstina Kolasin"),
            ("ME-10", "Kotor"),
            ("ME-11", "Mojkovac"),
            ("ME-12", "Opstina Niksic"),
            ("ME-13", "Opstina Plav"),
            ("ME-14", "Pljevlja"),
            ("ME-15", "Opstina Pluzine"),
            ("ME-16", "Podgorica"),
            ("ME-17", "Opstina Rozaje"),
            ("ME-18", "Opstina Savnik"),
            ("ME-19", "Tivat"),
            ("ME-20", "Ulcinj"),
            ("ME-21", "Opstina Zabljak"),
            ("ME-22", "Gusinje"),
            ("ME-23", "Petnjica"),
            ("ME-24", "Tuzi"),
        ],
    ),
    (
        "RS",
        &[
            ("RS-00", "Beograd"),
            ("RS-01", "Severnobacki okrug"),
            ("RS-02", "Srednjebanatski okrug"),
            ("RS-03", "Severnobanatski okrug"),
            ("RS-04", "Juznobanatski okrug"),
            ("RS-05", "Zapadnobacki okrug"),
            ("RS-06", "Juznobacki okrug"),
            ("RS-07", "Sremski okrug"),
            ("RS-08", "Macvanski okrug"),
            ("RS-09", "Kolubarski okrug"),
            ("RS-10", "Podunavski okrug"),
            ("RS-11", "Branicevski okrug"),
            ("RS-12", "Sumadijski okrug"),
            ("RS-13", "Pomoravski okrug"),
            ("RS-14", "Borski okrug"),
            ("RS-15", "Zajecarski okrug"),
            ("RS-16", "Zlatiborski okrug"),
            ("RS-17", "Moravicki okrug"),
            ("RS-18", "Raski okrug"),
            ("RS-19", "Rasinski okrug"),
            ("RS-20", "Nisavski okrug"),
            ("RS-21", "Toplicki okrug"),
            ("RS-22", "Pirotski okrug"),
            ("RS-23", "Jablanicki okrug"),
            ("RS-24", "Pcinjski okrug"),
        ],
    ),
    (
        "SI",
        &[
            ("SI-001", "Ajdovscina"),
            ("SI-002", "Beltinci"),
            ("SI-003", "Bled"),
            ("SI-004", "Bohinj"),
            ("SI-005", "Borovnica"),
            ("SI-006", "Bovec"),
            ("SI-007", "Brda"),
            ("SI-008", "Brezovica"),
            ("SI-009", "Brezice"),
            ("SI-010", "Tisina"),
            ("SI-011", "Celje"),
            ("SI-012", "Cerklje na Gorenjskem"),
            ("SI-013", "Cerknica"),
            ("SI-014", "Cerkno"),
            ("SI-015", "Crensovci"),
            ("SI-016", "Črna na Koroškem"),
            ("SI-017", "Crnomelj"),
            ("SI-018", "Destrnik"),
            ("SI-019", "Divaca"),
            ("SI-020", "Dobrepolje"),
            ("SI-021", "Dobrova-Polhov Gradec"),
            ("SI-022", "Dol pri Ljubljani"),
            ("SI-023", "Domzale"),
            ("SI-024", "Dornava"),
            ("SI-025", "Dravograd"),
            ("SI-026", "Duplek"),
            ("SI-027", "Gorenja vas-Poljane"),
            ("SI-028", "Gorišnica"),
            ("SI-029", "Gornja Radgona"),
            ("SI-030", "Gornji Grad"),
            ("SI-031", "Gornji Petrovci"),
            ("SI-032", "Grosuplje"),
            ("SI-033", "Salovci"),
            ("SI-034", "Hrastnik"),
            ("SI-035", "Hrpelje-Kozina"),
            ("SI-036", "Idrija"),
            ("SI-037", "Ig"),
            ("SI-038", "Ilirska Bistrica"),
            ("SI-039", "Ivancna Gorica"),
            ("SI-040", "Izola"),
            ("SI-041", "Jesenice"),
            ("SI-042", "Jursinci"),
            ("SI-043", "Kamnik"),
            ("SI-044", "Kanal"),
            ("SI-045", "Kidricevo"),
            ("SI-046", "Kobarid"),
            ("SI-047", "Kobilje"),
            ("SI-048", "Kocevje"),
            ("SI-049", "Komen"),
            ("SI-050", "Koper"),
            ("SI-051", "Kozje"),
            ("SI-052", "Kranj"),
            ("SI-053", "Kranjska Gora"),
            ("SI-054", "Krsko"),
            ("SI-055", "Kungota"),
            ("SI-056", "Kuzma"),
            ("SI-057", "Lasko"),
            ("SI-058", "Lenart"),
            ("SI-059", "Lendava"),
            ("SI-060", "Litija"),
            ("SI-061", "Ljubljana"),
            ("SI-062", "Ljubno"),
            ("SI-063", "Ljutomer"),
            ("SI-064", "Logatec"),
            ("SI-065", "Loska dolina"),
            ("SI-066", "Loski Potok"),
            ("SI-067", "Luce"),
            ("SI-068", "Lukovica"),
            ("SI-069", "Majsperk"),
            ("SI-070", "Maribor"),
            ("SI-071", "Medvode"),
            ("SI-072", "Menges"),
            ("SI-073", "Metlika"),
            ("SI-074", "Mezica"),
            ("SI-075", "Miren-Kostanjevica"),
            ("SI-076", "Mislinja"),
            ("SI-077", "Moravce"),
            ("SI-078", "Moravske Toplice"),
            ("SI-079", "Mozirje"),
            ("SI-080", "Murska Sobota"),
            ("SI-081", "Muta"),
            ("SI-082", "Naklo"),
            ("SI-083", "Nazarje"),
            ("SI-084", "Nova Gorica"),
            ("SI-085", "Novo Mesto"),
            ("SI-086", "Odranci"),
            ("SI-087", "Ormoz"),
            ("SI-088", "Osilnica"),
            ("SI-089", "Pesnica"),
            ("SI-090", "Piran"),
            ("SI-091", "Pivka"),
            ("SI-092", "Podcetrtek"),
            ("SI-093", "Podvelka"),
            ("SI-094", "Postojna"),
            ("SI-095", "Preddvor"),
            ("SI-096", "Ptuj"),
            ("SI-097", "Puconci"),
            ("SI-098", "Race-Fram"),
            ("SI-099", "Radece"),
            ("SI-100", "Radenci"),
            ("SI-101", "Radlje ob Dravi"),
            ("SI-102", "Radovljica"),
            ("SI-103", "Ravne na Koroskem"),
            ("SI-104", "Ribnica"),
            ("SI-105", "Rogasovci"),
            ("SI-106", "Rogaska Slatina"),
            ("SI-107", "Rogatec"),
            ("SI-108", "Ruse"),
            ("SI-109", "Semic"),
            ("SI-110", "Sevnica"),
            ("SI-111", "Sezana"),
            ("SI-112", "Slovenj Gradec"),
            ("SI-113", "Slovenska Bistrica"),
            ("SI-114", "Slovenske Konjice"),
            ("SI-115", "Starse"),
            ("SI-116", "Sveti Jurij ob Scavnici"),
            ("SI-117", "Sencur"),
            ("SI-118", "Sentilj"),
            ("SI-119", "Sentjernej"),
            ("SI-120", "Sentjur"),
            ("SI-121", "Skocjan"),
            ("SI-122", "Skofja Loka"),
            ("SI-123", "Skofljica"),
            ("SI-124", "Smarje pri Jelsah"),
            ("SI-125", "Smartno ob Paki"),
            ("SI-126", "Sostanj"),
            ("SI-127", "Store"),
            ("SI-128", "Tolmin"),
            ("SI-129", "Trbovlje"),
            ("SI-130", "Trebnje"),
            ("SI-131", "Trzic"),
            ("SI-132", "Turnisce"),
            ("SI-133", "Velenje"),
            ("SI-134", "Velike Lasce"),
            ("SI-135", "Videm"),
            ("SI-136", "Vipava"),
            ("SI-137", "Vitanje"),
            ("SI-138", "Vodice"),
            ("SI-139", "Vojnik"),
            ("SI-140", "Vrhnika"),
            ("SI-141", "Vuzenica"),
            ("SI-142", "Zagorje ob Savi"),
            ("SI-143", "Zavrc"),
            ("SI-144", "Zrece"),
            ("SI-146", "Zelezniki"),
            ("SI-147", "Ziri"),
            ("SI-148", "Benedikt"),
            ("SI-149", "Bistrica ob Sotli"),
            ("SI-150", "Bloke"),
            ("SI-151", "Braslovce"),
            ("SI-152", "Cankova"),
            ("SI-153", "Cerkvenjak"),
            ("SI-154", "Dobje"),
            ("SI-155", "Dobrna"),
            ("SI-156", "Dobrovnik"),
            ("SI-157", "Dolenjske Toplice"),
            ("SI-158", "Grad"),
            ("SI-159", "Hajdina"),
            ("SI-160", "Hoce-Slivnica"),
            ("SI-161", "Hodos"),
            ("SI-162", "Horjul"),
            ("SI-163", "Jezersko"),
            ("SI-164", "Komenda"),
            ("SI-165", "Kostel"),
            ("SI-166", "Krizevci"),
            ("SI-167", "Lovrenc na Pohorju"),
            ("SI-168", "Markovci"),
            ("SI-169", "Miklavz na Dravskem polju"),
            ("SI-170", "Mirna Pec"),
            ("SI-171", "Oplotnica"),
            ("SI-172", "Podlehnik"),
            ("SI-173", "Polzela"),
            ("SI-174", "Prebold"),
            ("SI-175", "Prevalje"),
            ("SI-176", "Razkrizje"),
            ("SI-177", "Ribnica na Pohorju"),
            ("SI-178", "Selnica ob Dravi"),
            ("SI-179", "Sodrazica"),
            ("SI-180", "Solcava"),
            ("SI-181", "Sveta Ana"),
            ("SI-182", "Sveti Andraz v Slovenskih Goricah"),
            ("SI-183", "Sempeter-Vrtojba"),
            ("SI-184", "Tabor"),
            ("SI-185", "Trnovska Vas"),
            ("SI-186", "Trzin"),
            ("SI-187", "Velika Polana"),
            ("SI-188", "Verzej"),
            ("SI-189", "Vransko"),
            ("SI-190", "Zalec"),
            ("SI-191", "Zetale"),
            ("SI-192", "Žirovnica"),
            ("SI-193", "Zuzemberk"),
            ("SI-194", "Smartno pri Litiji"),
            ("SI-195", "Apace"),
            ("SI-196", "Cirkulane"),
            ("SI-197", "Kosanjevica na Krki"),
            ("SI-198", "Makole"),
            ("SI-199", "Mokronog-Trebelno"),
            ("SI-200", "Poljcane"),
            ("SI-201", "Rence-Vogrsko"),
            ("SI-202", "Središče ob Dravi"),
            ("SI-203", "Straza"),
            ("SI-204", "Sveta Trojica v Slovenskih goricah"),
            ("SI-205", "Sveti Tomaz"),
            ("SI-206", "Smarjeske Toplice"),
            ("SI-207", "Gorje"),
            ("SI-208", "Log-Dragomer"),
            ("SI-209", "Recica ob Savinji"),
            ("SI-210", "Sveti Jurij v Slovenskih goricah"),
            ("SI-211", "Sentrupert"),
            ("SI-212", "Mirna"),
            ("SI-213", "Ankaran"),
        ],
    ),
    (
        "CH",
        &[
            ("CH-AG", "Kanton Aargau"),
            ("CH-AI", "Kanton Appenzell Innerrhoden"),
            ("CH-AR", "Kanton Appenzell Ausserrhoden"),
            ("CH-BE", "Canton de Berne"),
            ("CH-BL", "Kanton Basel-Landschaft"),
            ("CH-BS", "Kanton Basel-Stadt"),
            ("CH-FR", "Canton de Fribourg"),
            ("CH-GE", "Canton de Geneve"),
            ("CH-GL", "Kanton Glarus"),
            ("CH-GR", "Kanton Graubunden"),
            ("CH-JU", "Canton de Jura"),
            ("CH-LU", "Kanton Luzern"),
            ("CH-NE", "Canton de Neuchatel"),
            ("CH-NW", "Kanton Nidwalden"),
            ("CH-OW", "Kanton Obwalden"),
            ("CH-SG", "Kanton St. Gallen"),
            ("CH-SH", "Kanton Schaffhausen"),
            ("CH-SO", "Kanton Solothurn"),
            ("CH-SZ", "Kanton Schwyz"),
            ("CH-TG", "Kanton Thurgau"),
            ("CH-TI", "Cantone Ticino"),
            ("CH-UR", "Kanton Uri"),
            ("CH-VD", "Canton de Vaud"),
            ("CH-VS", "Canton du Valais"),
            ("CH-ZG", "Kanton Zug"),
            ("CH-ZH", "Kanton Zurich"),
        ],
    ),
    (
        "AD",
        &[
            ("AD-02", "Canillo"),
            ("AD-03", "Encamp"),
            ("AD-04", "La Massana"),
            ("AD-05", "Ordino"),
            ("AD-06", "Sant Julia de Loria"),
            ("AD-07", "Andorra la Vella"),
            ("AD-08", "Escaldes-Engordany"),
        ],
    ),
    (
        "SM",
        &[
            ("SM-01", "Castello di Acquaviva"),
            ("SM-02", "Chiesanuova"),
            ("SM-03", "Domagnano"),
            ("SM-04", "Castello di Faetano"),
            ("SM-05", "Castello di Fiorentino"),
            ("SM-06", "Castello di Borgo Maggiore"),
            ("SM-07", "San Marino"),
            ("SM-08", "Castello di Montegiardino"),
            ("SM-09", "Serravalle"),
        ],
    ),
    ("MC", &[("MC-1", "Monaco")]),
    ("GI", &[("Gibraltar", "Gibraltar")]),
    (
        "IE",
        &[
            ("IE-CE", "Clare"),
            ("IE-CN", "Cavan"),
            ("IE-CO", "Cork"),
            ("IE-CW", "Carlow"),
            ("IE-D", "Dublin"),
            ("IE-DL", "Donegal"),
            ("IE-G", "Galway"),
            ("IE-KE", "Kildare"),
            ("IE-KK", "Kilkenny"),
            ("IE-KY", "Kerry"),
            ("IE-LD", "Longford"),
            ("IE-LH", "Louth"),
            ("IE-LK", "Limerick"),
            ("IE-LM", "Leitrim"),
            ("IE-LS", "Laois"),
            ("IE-MH", "Meath"),
            ("IE-MN", "Monaghan"),
            ("IE-MO", "Mayo"),
            ("IE-OY", "Offaly"),
            ("IE-RN", "Roscommon"),
            ("IE-SO", "Sligo"),
            ("IE-TA", "Tipperary"),
            ("IE-WD", "Waterford"),
            ("IE-WH", "Westmeath"),
            ("IE-WW", "Wicklow"),
            ("IE-WX", "Wexford"),
        ],
    ),
    (
        "GB",
        &[
            ("GB-ENG", "England"),
            ("GB-NIR", "Northern Ireland"),
            ("GB-SCT", "Scotland"),
            ("GB-WLS", "Wales"),
        ],
    ),
    (
        "TR",
        &[
            ("TR-01", "Adana"),
            ("TR-02", "Adiyaman"),
            ("TR-03", "Afyonkarahisar"),
            ("TR-04", "Agri"),
            ("TR-05", "Amasya"),
            ("TR-06", "Ankara"),
            ("TR-07", "Antalya"),
            ("TR-08", "Artvin"),
            ("TR-09", "Aydin"),
            ("TR-10", "Balikesir"),
            ("TR-11", "Bilecik"),
            ("TR-12", "Bingol"),
            ("TR-13", "Bitlis"),
            ("TR-14", "Bolu"),
            ("TR-15", "Burdur"),
            ("TR-16", "Bursa"),
            ("TR-17", "Canakkale"),
            ("TR-18", "Cankiri"),
            ("TR-19", "Corum"),
            ("TR-20", "Denizli"),
            ("TR-21", "Diyarbakir"),
            ("TR-22", "Edirne"),
            ("TR-23", "Elazig"),
            ("TR-24", "Erzincan"),
            ("TR-25", "Erzurum"),
            ("TR-26", "Eskisehir"),
            ("TR-27", "Gaziantep"),
            ("TR-28", "Giresun"),
            ("TR-29", "Gumushane"),
            ("TR-30", "Hakkari"),
            ("TR-31", "Hatay"),
            ("TR-32", "Isparta"),
            ("TR-33", "Mersin"),
            ("TR-34", "Istanbul"),
            ("TR-35", "Izmir"),
            ("TR-36", "Kars"),
            ("TR-37", "Kastamonu"),
            ("TR-38", "Kayseri"),
            ("TR-39", "Kirklareli"),
            ("TR-40", "Kirsehir"),
            ("TR-41", "Kocaeli"),
            ("TR-42", "Konya"),
            ("TR-43", "Kutahya"),
            ("TR-44", "Malatya"),
            ("TR-45", "Manisa"),
            ("TR-46", "Kahramanmaras"),
            ("TR-47", "Mardin"),
            ("TR-48", "Mugla"),
            ("TR-49", "Mus"),
            ("TR-50", "Nevsehir"),
            ("TR-51", "Nigde"),
            ("TR-52", "Ordu"),
            ("TR-53", "Rize"),
            ("TR-54", "Sakarya"),
            ("TR-55", "Samsun"),
            ("TR-56", "Siirt"),
            ("TR-57", "Sinop"),
            ("TR-58", "Sivas"),
            ("TR-59", "Tekirdag"),
            ("TR-60", "Tokat"),
            ("TR-61", "Trabzon"),
            ("TR-62", "Tunceli"),
            ("TR-63", "Sanliurfa"),
            ("TR-64", "Usak"),
            ("TR-65", "Van"),
            ("TR-66", "Yozgat"),
            ("TR-67", "Zonguldak"),
            ("TR-68", "Aksaray"),
            ("TR-69", "Bayburt"),
            ("TR-70", "Karaman"),
            ("TR-71", "Kirikkale"),
            ("TR-72", "Batman"),
            ("TR-73", "Sirnak"),
            ("TR-74", "Bartin"),
            ("TR-75", "Ardahan"),
            ("TR-76", "Igdir"),
            ("TR-77", "Yalova"),
            ("TR-78", "Karabuk"),
            ("TR-79", "Kilis"),
            ("TR-80", "Osmaniye"),
            ("TR-81", "Duzce"),
        ],
    ),
    (
        "UA",
        &[
            ("UA-05", "Vinnytsya Oblast"),
            ("UA-07", "Volynska Oblast"),
            ("UA-12", "Dnipropetrovsk Oblast"),
            ("UA-14", "Donetska Oblast"),
            ("UA-18", "Zhytomyrska Oblast"),
            ("UA-21", "Zakarpattia Oblast"),
            ("UA-23", "Zaporizhzhya Oblast"),
            ("UA-26", "Ivano-Frankivsk Oblast"),
            ("UA-30", "Kyiv"),
            ("UA-32", "Kyiv Oblast"),
            ("UA-35", "Kirovohrad Oblast"),
            ("UA-46", "Lvivska Oblast"),
            ("UA-48", "Mykolayiv Oblast"),
            ("UA-51", "Odeska Oblast"),
            ("UA-53", "Poltava Oblast"),
            ("UA-56", "Rivnenska Oblast"),
            ("UA-59", "Sumska Oblast"),
            ("UA-61", "Ternopil Oblast"),
            ("UA-63", "Kharkivska Oblast"),
            ("UA-65", "Kherson Oblast"),
            ("UA-68", "Khmelnytskyi Oblast"),
            ("UA-71", "Cherkasy Oblast"),
            ("UA-74", "Chernihivska Oblast"),
            ("UA-77", "Chernivtsi Oblast"),
        ],
    ),
    (
        "AL",
        &[
            ("AL-01", "Qarku i Beratit"),
            ("AL-02", "Qarku i Durresit"),
            ("AL-03", "Qarku i Elbasanit"),
            ("AL-04", "Qarku i Fierit"),
            ("AL-05", "Qarku i Gjirokastres"),
            ("AL-06", "Qarku i Korces"),
            ("AL-07", "Qarku i Kukesit"),
            ("AL-08", "Qarku i Lezhes"),
            ("AL-09", "Qarku i Dibres"),
            ("AL-10", "Qarku i Shkodres"),
            ("AL-11", "Tirana"),
            ("AL-12", "Qarku i Vlores"),
        ],
    ),
    (
        "FO",
        &[
            ("Norðoyar region", "Norðoyar region"),
            ("Streymoy region", "Streymoy region"),
            ("Vágar region", "Vágar region"),
            ("Eysturoy region", "Eysturoy region"),
            ("Sandoy region", "Sandoy region"),
            ("Suðuroy region", "Suðuroy region"),
        ],
    ),
    (
        "MT",
        &[
            ("MT-01", "Attard"),
            ("MT-02", "Balzan"),
            ("MT-03", "Birgu"),
            ("MT-04", "Birkirkara"),
            ("MT-05", "Birzebbuga"),
            ("MT-06", "Bormla"),
            ("MT-07", "Dingli"),
            ("MT-08", "Fgura"),
            ("MT-09", "Floriana"),
            ("MT-10", "Fontana"),
            ("MT-11", "Gudja"),
            ("MT-12", "Gzira"),
            ("MT-13", "Ghajnsielem"),
            ("MT-14", "Gharb"),
            ("MT-15", "Gharghur"),
            ("MT-16", "Ghasri"),
            ("MT-17", "Ghaxaq"),
            ("MT-18", "Hamrun"),
            ("MT-19", "Iklin"),
            ("MT-20", "Isla"),
            ("MT-21", "Kalkara"),
            ("MT-22", "Kerċem"),
            ("MT-23", "Kirkop"),
            ("MT-24", "Lija"),
            ("MT-25", "Luqa"),
            ("MT-26", "Marsa"),
            ("MT-27", "Marsaskala"),
            ("MT-28", "Marsaxlokk"),
            ("MT-29", "Mdina"),
            ("MT-30", "Mellieha"),
            ("MT-31", "Mgarr"),
            ("MT-32", "Mosta"),
            ("MT-33", "Mqabba"),
            ("MT-34", "Msida"),
            ("MT-35", "Mtarfa"),
            ("MT-36", "Munxar"),
            ("MT-37", "Nadur"),
            ("MT-38", "Naxxar"),
            ("MT-39", "Paola"),
            ("MT-40", "Pembroke"),
            ("MT-41", "Pieta"),
            ("MT-42", "Qala"),
            ("MT-43", "Qormi"),
            ("MT-44", "Qrendi"),
            ("MT-45", "Rabat Gozo"),
            ("MT-46", "Rabat Malta"),
            ("MT-47", "Safi"),
            ("MT-48", "Saint Julian's"),
            ("MT-49", "Saint John"),
            ("MT-50", "Saint Lawrence"),
            ("MT-51", "Saint Paul's Bay"),
            ("MT-52", "Sannat"),
            ("MT-53", "Saint Lucia's"),
            ("MT-54", "Santa Venera"),
            ("MT-55", "Siggiewi"),
            ("MT-56", "Sliema"),
            ("MT-57", "Swieqi"),
            ("MT-58", "Ta' Xbiex"),
            ("MT-59", "Tarxien"),
            ("MT-60", "Valletta"),
            ("MT-61", "Xaghra"),
            ("MT-62", "Xewkija"),
            ("MT-63", "Xghajra"),
            ("MT-64", "Zabbar"),
            ("MT-65", "Zebbug Gozo"),
            ("MT-66", "Żebbuġ Malta"),
            ("MT-67", "Zejtun"),
            ("MT-68", "Zurrieq"),
        ],
    ),
    (
        "RU",
        &[
            ("RU-AD", "Adygea"),
            ("RU-AL", "Gorno-Altai"),
            ("RU-ALT", "Altai"),
            ("RU-AMU", "Amur"),
            ("RU-ARK", "Arkhangelsk"),
            ("RU-AST", "Astrakhan"),
            ("RU-BA", "Bashkortostan"),
            ("RU-BEL", "Belgorod"),
            ("RU-BRY", "Bryansk"),
            ("RU-BU", "Buryatia"),
            ("RU-CE", "Chechnya"),
            ("RU-CHE", "Chelyabinsk"),
            ("RU-CU", "Chuvashia"),
            ("RU-DA", "Dagestan"),
            ("RU-IN", "Ingushetia"),
            ("RU-IRK", "Irkutsk"),
            ("RU-IVA", "Ivanovo"),
            ("RU-KAM", "Kamchatka"),
            ("RU-KB", "Kabardino-Balkaria"),
            ("RU-KC", "Karachay-Cherkessia"),
            ("RU-KDA", "Krasnodar"),
            ("RU-KEM", "Kemerovo"),
            ("RU-KGD", "Kaliningrad"),
            ("RU-KGN", "Kurgan"),
            ("RU-KHA", "Khabarovsk"),
            ("RU-KHM", "Yugoria"),
            ("RU-KIR", "Kirov"),
            ("RU-KK", "Khakassia"),
            ("RU-KL", "Kalmykia"),
            ("RU-KLU", "Kaluga"),
            ("RU-KO", "Komi"),
            ("RU-KOS", "Kostroma"),
            ("RU-KR", "Karelia"),
            ("RU-KRS", "Kursk"),
            ("RU-KYA", "Krasnoyarsk"),
            ("RU-LEN", "Leningrad"),
            ("RU-LIP", "Lipetsk"),
            ("RU-MAG", "Magadan"),
            ("RU-ME", "Mari El"),
            ("RU-MO", "Mordovia"),
            ("RU-MOS", "Moscow"),
            ("RU-MOW", "Moscow City"),
            ("RU-MUR", "Murmansk"),
            ("RU-NEN", "Nenetsia"),
            ("RU-NGR", "Novgorod"),
            ("RU-NIZ", "Nizhny Novgorod"),
            ("RU-NVS", "Novosibirsk"),
            ("RU-OMS", "Omsk"),
            ("RU-ORE", "Orenburg"),
            ("RU-ORL", "Oryol"),
            ("RU-PER", "Perm"),
            ("RU-PNZ", "Penza"),
            ("RU-PRI", "Primorye"),
            ("RU-PSK", "Pskov"),
            ("RU-ROS", "Rostov"),
            ("RU-RYA", "Ryazan"),
            ("RU-SA", "Yakutia"),
            ("RU-SAK", "Sakhalin"),
            ("RU-SAM", "Samara"),
            ("RU-SAR", "Saratov"),
            ("RU-SE", "North Ossetia"),
            ("RU-SMO", "Smolensk"),
            ("RU-SPE", "Saint Petersburg"),
            ("RU-STA", "Stavropol"),
            ("RU-SVE", "Sverdlovsk"),
            ("RU-TA", "Tatarstan"),
            ("RU-TAM", "Tambov"),
            ("RU-TOM", "Tomsk"),
            ("RU-TUL", "Tula"),
            ("RU-TVE", "Tver"),
            ("RU-TY", "Tuva"),
            ("RU-TYU", "Tyumen"),
            ("RU-UD", "Udmurtia"),
            ("RU-ULY", "Ulyanovsk"),
            ("RU-VGG", "Volgograd"),
            ("RU-VLA", "Vladimir"),
            ("RU-VLG", "Vologda"),
            ("RU-VOR", "Voronezh"),
            ("RU-YAN", "Yamalia"),
            ("RU-YAR", "Yaroslavl"),
            ("RU-YEV", "Jewish Autonomous Oblast"),
            ("RU-ZAB", "Transbaikalia"),
        ],
    ),
    (
        "NG",
        &[
            ("NG-AB", "Abia"),
            ("NG-AD", "Adamawa"),
            ("NG-AK", "Akwa Ibom"),
            ("NG-AN", "Anambra"),
            ("NG-BA", "Bauchi"),
            ("NG-BE", "Benue"),
            ("NG-BO", "Borno"),
            ("NG-BY", "Bayelsa"),
            ("NG-CR", "Cross River"),
            ("NG-DE", "Delta"),
            ("NG-EB", "Ebonyi"),
            ("NG-ED", "Edo"),
            ("NG-EK", "Ekiti"),
            ("NG-EN", "Enugu"),
            ("NG-FC", "Abuja Federal Capital Territory"),
            ("NG-GO", "Gombe"),
            ("NG-IM", "Imo"),
            ("NG-JI", "Jigawa"),
            ("NG-KD", "Kaduna"),
            ("NG-KE", "Kebbi"),
            ("NG-KN", "Kano"),
            ("NG-KO", "Kogi"),
            ("NG-KT", "Katsina"),
            ("NG-KW", "Kwara"),
            ("NG-LA", "Lagos"),
            ("NG-NA", "Nasarawa"),
            ("NG-NI", "Niger"),
            ("NG-OG", "Ogun"),
            ("NG-ON", "Ondo"),
            ("NG-OS", "Osun"),
            ("NG-OY", "Oyo"),
            ("NG-PL", "Plateau"),
            ("NG-RI", "Rivers"),
            ("NG-SO", "Sokoto"),
            ("NG-TA", "Taraba"),
            ("NG-YO", "Yobe"),
            ("NG-ZA", "Zamfara"),
        ],
    ),
    (
        "SN",
        &[
            ("SN-DB", "Diourbel"),
            ("SN-DK", "Dakar"),
            ("SN-FK", "Fatick"),
            ("SN-KA", "Region de Kaffrine"),
            ("SN-KD", "Kolda"),
            ("SN-KE", "Region de Kedougou"),
            ("SN-KL", "Kaolack"),
            ("SN-LG", "Louga"),
            ("SN-MT", "Matam"),
            ("SN-SE", "Region de Sedhiou"),
            ("SN-SL", "Saint-Louis"),
            ("SN-TC", "Tambacounda"),
            ("SN-TH", "Region de Thies"),
            ("SN-ZG", "Ziguinchor"),
        ],
    ),
    (
        "TN",
        &[
            ("TN-11", "Gouvernorat de Tunis"),
            ("TN-12", "Gouvernorat de l’Ariana"),
            ("TN-13", "Gouvernorat de Ben Arous"),
            ("TN-14", "Manouba"),
            ("TN-21", "Gouvernorat de Nabeul"),
            ("TN-23", "Gouvernorat de Bizerte"),
            ("TN-41", "Gouvernorat de Kairouan"),
            ("TN-51", "Gouvernorat de Sousse"),
            ("TN-52", "Gouvernorat de Monastir"),
            ("TN-53", "Gouvernorat de Mahdia"),
            ("TN-61", "Gouvernorat de Sfax"),
            ("TN-81", "Gouvernorat de Gabes"),
            ("TN-82", "Gouvernorat de Medenine"),
        ],
    ),
    (
        "KE",
        &[
            ("KE-01", "Baringo"),
            ("KE-02", "Bomet"),
            ("KE-03", "Bungoma"),
            ("KE-04", "Busia"),
            ("KE-05", "Elgeyo/Marakwet"),
            ("KE-06", "Embu"),
            ("KE-07", "Garissa"),
            ("KE-08", "Homa Bay"),
            ("KE-09", "Isiolo"),
            ("KE-10", "Kajiado"),
            ("KE-11", "Kakamega"),
            ("KE-12", "Kericho"),
            ("KE-13", "Kiambu"),
            ("KE-14", "Kilifi"),
            ("KE-15", "Kirinyaga"),
            ("KE-16", "Kisii"),
            ("KE-17", "Kisumu"),
            ("KE-18", "Kitui"),
            ("KE-19", "Kwale"),
            ("KE-20", "Laikipia"),
            ("KE-22", "Machakos"),
            ("KE-23", "Makueni"),
            ("KE-25", "Marsabit"),
            ("KE-26", "Meru"),
            ("KE-27", "Migori"),
            ("KE-28", "Mombasa"),
            ("KE-29", "Murang'a"),
            ("KE-30", "Nairobi City"),
            ("KE-31", "Nakuru"),
            ("KE-32", "Nandi"),
            ("KE-33", "Narok"),
            ("KE-34", "Nyamira"),
            ("KE-35", "Nyandarua"),
            ("KE-36", "Nyeri"),
            ("KE-37", "Samburu"),
            ("KE-38", "Siaya"),
            ("KE-39", "Taita/Taveta"),
            ("KE-40", "Tana River"),
            ("KE-41", "Tharaka-Nithi"),
            ("KE-42", "Trans Nzoia"),
            ("KE-43", "Turkana"),
            ("KE-44", "Uasin Gishu"),
            ("KE-45", "Vihiga"),
            ("KE-46", "Wajir"),
            ("KE-47", "West Pokot"),
        ],
    ),
    (
        "ZA",
        &[
            ("ZA-EC", "Eastern Cape"),
            ("ZA-FS", "Free State"),
            ("ZA-GP", "Gauteng"),
            ("ZA-KZN", "Kwazulu-Natal"),
            ("ZA-LP", "Limpopo"),
            ("ZA-MP", "Mpumalanga"),
            ("ZA-NC", "Northern Cape"),
            ("ZA-NW", "North-West"),
            ("ZA-WC", "Western Cape"),
        ],
    ),
    (
        "BD",
        &[
            ("BD-A", "Barisal"),
            ("BD-B", "Chittagong"),
            ("BD-C", "Dhaka"),
            ("BD-D", "Khulna"),
            ("BD-E", "Rajshahi"),
            ("BD-F", "Rangpur"),
            ("BD-G", "Sylhet"),
            ("BD-H", "Mymensingh"),
        ],
    ),
    (
        "MY",
        &[
            ("MY-01", "Johor"),
            ("MY-02", "Kedah"),
            ("MY-03", "Kelantan"),
            ("MY-04", "Melaka"),
            ("MY-05", "Negeri Sembilan"),
            ("MY-06", "Pahang"),
            ("MY-07", "Pulau Pinang"),
            ("MY-08", "Perak"),
            ("MY-09", "Perlis"),
            ("MY-10", "Selangor"),
            ("MY-11", "Terengganu"),
            ("MY-12", "Sabah"),
            ("MY-13", "Sarawak"),
            ("MY-14", "Kuala Lumpur"),
            ("MY-15", "Labuan"),
            ("MY-16", "Putrajaya"),
        ],
    ),
    (
        "TH",
        &[
            ("TH-10", "Bangkok"),
            ("TH-11", "Changwat Samut Prakan"),
            ("TH-12", "Changwat Nonthaburi"),
            ("TH-13", "Changwat Pathum Thani"),
            ("TH-14", "Phra Nakhon Si Ayutthaya"),
            ("TH-15", "Changwat Ang Thong"),
            ("TH-16", "Changwat Lop Buri"),
            ("TH-17", "Changwat Sing Buri"),
            ("TH-18", "Changwat Chai Nat"),
            ("TH-19", "Changwat Saraburi"),
            ("TH-20", "Changwat Chon Buri"),
            ("TH-21", "Changwat Rayong"),
            ("TH-22", "Changwat Chanthaburi"),
            ("TH-23", "Changwat Trat"),
            ("TH-24", "Changwat Chachoengsao"),
            ("TH-25", "Changwat Prachin Buri"),
            ("TH-26", "Changwat Nakhon Nayok"),
            ("TH-27", "Changwat Sa Kaeo"),
            ("TH-30", "Changwat Nakhon Ratchasima"),
            ("TH-31", "Changwat Buri Ram"),
            ("TH-32", "Changwat Surin"),
            ("TH-33", "Changwat Si Sa Ket"),
            ("TH-34", "Changwat Ubon Ratchathani"),
            ("TH-35", "Changwat Yasothon"),
            ("TH-36", "Changwat Chaiyaphum"),
            ("TH-37", "Changwat Amnat Charoen"),
            ("TH-38", "Changwat Bueng Kan"),
            ("TH-39", "Changwat Nong Bua Lamphu"),
            ("TH-40", "Changwat Khon Kaen"),
            ("TH-41", "Changwat Udon Thani"),
            ("TH-42", "Changwat Loei"),
            ("TH-43", "Changwat Nong Khai"),
            ("TH-44", "Changwat Maha Sarakham"),
            ("TH-45", "Changwat Roi Et"),
            ("TH-46", "Changwat Kalasin"),
            ("TH-47", "Changwat Sakon Nakhon"),
            ("TH-48", "Changwat Nakhon Phanom"),
            ("TH-49", "Changwat Mukdahan"),
            ("TH-50", "Chiang Mai Province"),
            ("TH-51", "Changwat Lamphun"),
            ("TH-52", "Changwat Lampang"),
            ("TH-53", "Changwat Uttaradit"),
            ("TH-54", "Changwat Phrae"),
            ("TH-55", "Changwat Nan"),
            ("TH-56", "Changwat Phayao"),
            ("TH-57", "Changwat Chiang Rai"),
            ("TH-58", "Changwat Mae Hong Son"),
            ("TH-60", "Changwat Nakhon Sawan"),
            ("TH-61", "Changwat Uthai Thani"),
            ("TH-62", "Changwat Kamphaeng Phet"),
            ("TH-63", "Changwat Tak"),
            ("TH-64", "Changwat Sukhothai"),
            ("TH-65", "Changwat Phitsanulok"),
            ("TH-66", "Changwat Phichit"),
            ("TH-67", "Changwat Phetchabun"),
            ("TH-70", "Changwat Ratchaburi"),
            ("TH-71", "Changwat Kanchanaburi"),
            ("TH-72", "Changwat Suphan Buri"),
            ("TH-73", "Changwat Nakhon Pathom"),
            ("TH-74", "Changwat Samut Sakhon"),
            ("TH-75", "Changwat Samut Songkhram"),
            ("TH-76", "Changwat Phetchaburi"),
            ("TH-77", "Changwat Prachuap Khiri Khan"),
            ("TH-80", "Changwat Nakhon Si Thammarat"),
            ("TH-81", "Changwat Krabi"),
            ("TH-82", "Changwat Phangnga"),
            ("TH-83", "Phuket Province"),
            ("TH-84", "Changwat Surat Thani"),
            ("TH-85", "Changwat Ranong"),
            ("TH-86", "Changwat Chumphon"),
            ("TH-90", "Changwat Songkhla"),
            ("TH-91", "Changwat Satun"),
            ("TH-92", "Changwat Trang"),
            ("TH-93", "Changwat Phatthalung"),
            ("TH-94", "Changwat Pattani"),
            ("TH-95", "Changwat Yala"),
            ("TH-96", "Changwat Narathiwat"),
        ],
    ),
    (
        "LA",
        &[
            ("LA-CH", "Champasak"),
            ("LA-LP", "Luang Prabang Province"),
            ("LA-SV", "Khoueng Savannakhet"),
            ("LA-VI", "Vientiane Province"),
            ("LA-VT", "Vientiane Prefecture"),
            ("LA-XA", "Xaignabouli"),
        ],
    ),
    (
        "PH",
        &[
            ("PH-00", "National Capital Region"),
            ("PH-01", "Ilocos"),
            ("PH-02", "Cagayan Valley"),
            ("PH-03", "Central Luzon"),
            ("PH-05", "Bicol"),
            ("PH-06", "Western Visayas"),
            ("PH-07", "Central Visayas"),
            ("PH-08", "Eastern Visayas"),
            ("PH-09", "Zamboanga del Norte"),
            ("PH-10", "Northern Mindanao"),
            ("PH-11", "Davao"),
            ("PH-12", "Soccsksargen"),
            ("PH-13", "Caraga"),
            ("PH-14", "Autonomous Region in Muslim Mindanao"),
            ("PH-15", "Cordillera Administrative Region"),
            ("PH-40", "Calabarzon"),
            ("PH-41", "Mimaropa"),
        ],
    ),
    (
        "LK",
        &[
            ("LK-1", "Western Province"),
            ("LK-2", "Central Province"),
            ("LK-3", "Southern Province"),
            ("LK-4", "Northern Province"),
            ("LK-5", "Eastern Province"),
            ("LK-6", "North Western Province"),
            ("LK-7", "North Central Province"),
            ("LK-8", "Uva Province"),
            ("LK-9", "Sabaragamuwa Province"),
        ],
    ),
    (
        "IN",
        &[
            ("IN-AP", "Andhra Pradesh"),
            ("IN-AR", "Arunachal Pradesh"),
            ("IN-AS", "Assam"),
            ("IN-BR", "Bihar"),
            ("IN-CH", "Chandigarh"),
            ("IN-CT", "Chhattisgarh"),
            ("IN-DL", "Delhi"),
            ("IN-GA", "Goa"),
            ("IN-GJ", "Gujarat"),
            ("IN-HP", "Himachal Pradesh"),
            ("IN-HR", "Haryana"),
            ("IN-JH", "Jharkhand"),
            ("IN-KA", "Karnataka"),
            ("IN-KL", "Kerala"),
            ("IN-LA", "Ladakh"),
            ("IN-LD", "Lakshadweep"),
            ("IN-MH", "Maharashtra"),
            ("IN-ML", "Meghalaya"),
            ("IN-MN", "Manipur"),
            ("IN-MP", "Madhya Pradesh"),
            ("IN-MZ", "Mizoram"),
            ("IN-NL", "Nāgāland"),
            ("IN-OR", "Odisha"),
            ("IN-PB", "Punjab"),
            ("IN-PY", "Puducherry"),
            ("IN-RJ", "Rajasthan"),
            ("IN-SK", "Sikkim"),
            ("IN-TG", "Telangana"),
            ("IN-TN", "Tamil Nadu"),
            ("IN-TR", "Tripura"),
            ("IN-UP", "Uttar Pradesh"),
            ("IN-UT", "Uttarakhand"),
            ("IN-WB", "West Bengal"),
            ("IN-DH", "Dadra and Nagar Haveli and Daman and Diu"),
            ("IN-JK", "Jammu and Kashmir"),
            ("IN-AN", "Andaman and Nicobar Islands"),
        ],
    ),
    ("MG", &[("MG-U", "Toliara Province")]),
    (
        "BW",
        &[
            ("BW-CE", "Central"),
            ("BW-CH", "Chobe"),
            ("BW-GH", "Ghanzi"),
            ("BW-KG", "Kgalagadi"),
            ("BW-KL", "Kgatleng"),
            ("BW-KW", "Kweneng"),
            ("BW-NE", "North East"),
            ("BW-NW", "North West"),
            ("BW-SE", "Gaborone"),
            ("BW-SO", "Southern"),
        ],
    ),
    (
        "GH",
        &[
            ("GH-AA", "Greater Accra"),
            ("GH-AF", "Ahafo"),
            ("GH-AH", "Ashanti"),
            ("GH-BE", "Bono East"),
            ("GH-BO", "Bono"),
            ("GH-CP", "Central"),
            ("GH-EP", "Eastern"),
            ("GH-NE", "North East"),
            ("GH-NP", "Northern"),
            ("GH-OT", "Oti"),
            ("GH-SV", "Savannah"),
            ("GH-TV", "Volta"),
            ("GH-UE", "Upper East"),
            ("GH-UW", "Upper West"),
            ("GH-WN", "Western North"),
            ("GH-WP", "Western"),
        ],
    ),
    (
        "LS",
        &[
            ("LS-A", "Maseru"),
            ("LS-B", "Botha-Bothe"),
            ("LS-C", "Leribe"),
            ("LS-D", "Berea"),
            ("LS-E", "Mafeteng"),
            ("LS-F", "Mohale's Hoek"),
            ("LS-G", "Quthing"),
            ("LS-H", "Qacha's Nek"),
            ("LS-J", "Mokhotlong"),
            ("LS-K", "Thaba-Tseka"),
        ],
    ),
    (
        "RW",
        &[
            ("RW-01", "City of Kigali"),
            ("RW-02", "Eastern"),
            ("RW-03", "Northern"),
            ("RW-04", "Western"),
            ("RW-05", "Southern"),
        ],
    ),
    ("EG", &[("EG-C", "Cairo Governorate"), ("EG-GZ", "Muḩafazat al Jizah")]),
    ("PN", &[("PN-1", "Pitcairn")]),
    ("AS", &[("US-AS", "American Samoa")]),
    ("GU", &[("US-GU", "Guam")]),
    ("MP", &[("US-MP", "Northern Mariana Islands")]),
    (
        "QA",
        &[
            ("QA-DA", "Doha"),
            ("QA-KH", "Baladiyat al Khawr wa adh Dhakhirah"),
            ("QA-MS", "Madinat ash Shamal"),
            ("QA-RA", "Baladiyat ar Rayyan"),
            ("QA-SH", "Al-Shahaniya"),
            ("QA-US", "Baladiyat Umm Salal"),
            ("QA-WA", "Al Wakrah"),
            ("QA-ZA", "Baladiyat az Za‘ayin"),
        ],
    ),
    (
        "AE",
        &[
            ("AE-AJ", "Imarat ‘Ajman"),
            ("AE-AZ", "Abu Dhabi"),
            ("AE-DU", "Dubai"),
            ("AE-FU", "Imarat al Fujayrah"),
            ("AE-RK", "Imarat Ra’s al Khaymah"),
            ("AE-SH", "Ash Shariqah"),
            ("AE-UQ", "Imarat Umm al Qaywayn"),
        ],
    ),
    (
        "BT",
        &[
            ("BT-11", "Paro Dzongkhag"),
            ("BT-12", "Chhukha Dzongkhag"),
            ("BT-13", "Haa Dzongkhag"),
            ("BT-15", "Thimphu Dzongkhag"),
            ("BT-21", "Tsirang Dzongkhag"),
            ("BT-22", "Dagana Dzongkhag"),
            ("BT-23", "Punakha Dzongkhag"),
            ("BT-24", "Wangdue Phodrang Dzongkhag"),
            ("BT-31", "Sarpang Dzongkhag"),
            ("BT-32", "Trongsa Dzongkhag"),
            ("BT-33", "Bumthang Dzongkhag"),
            ("BT-34", "Zhemgang Dzongkhag"),
            ("BT-41", "Trashigang Dzongkhag"),
            ("BT-42", "Mongar Dzongkhag"),
            ("BT-43", "Pemagatshel Dzongkhag"),
            ("BT-44", "Lhuentse Dzongkhag"),
            ("BT-45", "Samdrup Jongkhar Dzongkhag"),
            ("BT-TY", "Trashi Yangste"),
        ],
    ),
    ("CX", &[("Christmas Island", "Christmas Island")]),
    ("CC", &[("Cocos (Keeling) Islands", "Cocos (Keeling) Islands")]),
    ("HK", &[("CN-HK", "Hong Kong")]),
    (
        "IL",
        &[
            ("IL-D", "Southern District"),
            ("IL-HA", "Haifa"),
            ("IL-JM", "Jerusalem"),
            ("IL-M", "Central District"),
            ("IL-TA", "Tel Aviv District"),
            ("IL-Z", "Northern District"),
        ],
    ),
    (
        "JO",
        &[
            ("JO-AM", "Al 'Asimah"),
            ("JO-AQ", "Al 'Aqabah"),
            ("JO-AT", "At Tafilah"),
            ("JO-AZ", "Az Zarqa'"),
            ("JO-BA", "Al Balqa'"),
            ("JO-JA", "Jarash"),
            ("JO-KA", "Al Karak"),
            ("JO-MD", "Madaba"),
            ("JO-MN", "Ma'an"),
        ],
    ),
    (
        "JP",
        &[
            ("JP-01", "Hokkaido"),
            ("JP-02", "Aomori"),
            ("JP-03", "Iwate"),
            ("JP-04", "Miyagi"),
            ("JP-05", "Akita"),
            ("JP-06", "Yamagata"),
            ("JP-07", "Fukushima"),
            ("JP-08", "Ibaraki"),
            ("JP-09", "Tochigi"),
            ("JP-10", "Gunma"),
            ("JP-11", "Saitama"),
            ("JP-12", "Chiba"),
            ("JP-13", "Tokyo"),
            ("JP-14", "Kanagawa"),
            ("JP-15", "Niigata"),
            ("JP-16", "Toyama"),
            ("JP-17", "Ishikawa"),
            ("JP-18", "Fukui"),
            ("JP-19", "Yamanashi"),
            ("JP-20", "Nagano"),
            ("JP-21", "Gifu"),
            ("JP-22", "Shizuoka"),
            ("JP-23", "Aichi"),
            ("JP-24", "Mie"),
            ("JP-25", "Shiga"),
            ("JP-26", "Kyoto"),
            ("JP-27", "Osaka"),
            ("JP-28", "Hyogo"),
            ("JP-29", "Nara"),
            ("JP-30", "Wakayama"),
            ("JP-31", "Tottori"),
            ("JP-32", "Shimane"),
            ("JP-33", "Okayama"),
            ("JP-34", "Hiroshima"),
            ("JP-35", "Yamaguchi"),
            ("JP-36", "Tokushima"),
            ("JP-37", "Kagawa"),
            ("JP-38", "Ehime"),
            ("JP-39", "Kochi"),
            ("JP-40", "Fukuoka"),
            ("JP-41", "Saga"),
            ("JP-42", "Nagasaki"),
            ("JP-43", "Kumamoto"),
            ("JP-44", "Oita"),
            ("JP-45", "Miyazaki"),
            ("JP-46", "Kagoshima"),
            ("JP-47", "Okinawa"),
        ],
    ),
    (
        "KG",
        &[
            ("KG-C", "Chuyskaya Oblast’"),
            ("KG-GB", "Gorod Bishkek"),
            ("KG-GO", "Osh"),
            ("KG-J", "Jalal-Abad oblast"),
            ("KG-N", "Naryn oblast"),
            ("KG-O", "Osh Oblasty"),
            ("KG-T", "Talas"),
            ("KG-Y", "Issyk-Kul Region"),
        ],
    ),
    (
        "KH",
        &[
            ("KH-1", "Banteay Mean Choay"),
            ("KH-10", "Kracheh"),
            ("KH-11", "Mondol Kiri"),
            ("KH-12", "Phnom Penh"),
            ("KH-13", "Preah Vihear"),
            ("KH-14", "Prey Veaeng"),
            ("KH-15", "Pousaat"),
            ("KH-16", "Rotanak Kiri"),
            ("KH-17", "Siem Reab"),
            ("KH-18", "Preah Sihanouk"),
            ("KH-19", "Stueng Traeng"),
            ("KH-2", "Baat Dambang"),
            ("KH-20", "Svaay Rieng"),
            ("KH-21", "Taakaev"),
            ("KH-22", "Otdar Mean Chey"),
            ("KH-23", "Kaeb"),
            ("KH-24", "Pailin"),
            ("KH-25", "Tbong Khmum"),
            ("KH-3", "Kampong Chaam"),
            ("KH-4", "Kampong Chhnang"),
            ("KH-5", "Kampong Spueu"),
            ("KH-6", "Kampong Thum"),
            ("KH-7", "Kampot"),
            ("KH-8", "Kandaal"),
            ("KH-9", "Kaoh Kong"),
        ],
    ),
    (
        "KR",
        &[
            ("KR-11", "Seoul-teukbyeolsi"),
            ("KR-26", "Busan-gwangyeoksi"),
            ("KR-27", "Daegu-gwangyeoksi"),
            ("KR-28", "Incheon-gwangyeoksi"),
            ("KR-29", "Gwangju-gwangyeoksi"),
            ("KR-30", "Daejeon-gwangyeoksi"),
            ("KR-31", "Ulsan-gwangyeoksi"),
            ("KR-41", "Gyeonggi-do"),
            ("KR-42", "Gangwon-do"),
            ("KR-43", "Chungcheongbuk-do"),
            ("KR-44", "Chungcheongnam-do"),
            ("KR-45", "Jeollabuk-do"),
            ("KR-46", "Jeollanam-do"),
            ("KR-47", "Gyeongsangbuk-do"),
            ("KR-48", "Gyeongsangnam-do"),
            ("KR-49", "Jeju-teukbyeoljachido"),
            ("KR-50", "Sejong"),
        ],
    ),
    (
        "SG",
        &[
            ("SG-01", "Central Singapore"),
            ("SG-02", "North East"),
            ("SG-03", "North West"),
            ("SG-04", "South East"),
            ("SG-05", "South West"),
        ],
    ),
    (
        "TW",
        &[
            ("TW-CHA", "Changhua"),
            ("TW-CYI", "Chiayi"),
            ("TW-CYQ", "Chiayi County"),
            ("TW-HSQ", "Hsinchu County"),
            ("TW-HSZ", "Hsinchu"),
            ("TW-HUA", "Hualien"),
            ("TW-ILA", "Yilan"),
            ("TW-KEE", "Keelung"),
            ("TW-KHH", "Kaohsiung"),
            ("TW-KIN", "Kinmen County"),
            ("TW-LIE", "Lienchiang"),
            ("TW-MIA", "Miaoli"),
            ("TW-NAN", "Nantou"),
            ("TW-NWT", "New Taipei"),
            ("TW-PEN", "Penghu County"),
            ("TW-PIF", "Pingtung"),
            ("TW-TAO", "Taoyuan"),
            ("TW-TNN", "Tainan"),
            ("TW-TPE", "Taipei"),
            ("TW-TTT", "Taitung"),
            ("TW-TXG", "Taichung"),
            ("TW-YUN", "Yunlin"),
        ],
    ),
    ("AX", &[("AX-1", "Åland Islands")]),
    ("BM", &[("BM-1", "Bermuda")]),
    ("VI", &[("US-VI", "United States Virgin Islands")]),
    (
        "GL",
        &[
            ("GL-AV", "Avannaata"),
            ("GL-KU", "Kujalleq"),
            ("GL-QE", "Qeqqata"),
            ("GL-QT", "Qeqertalik"),
            ("GL-SM", "Sermersooq"),
        ],
    ),
    (
        "CR",
        &[
            ("CR-A", "Alajuela"),
            ("CR-C", "Cartago"),
            ("CR-G", "Guanacaste"),
            ("CR-H", "Heredia"),
            ("CR-L", "Limón"),
            ("CR-P", "Puntarenas"),
            ("CR-SJ", "San José"),
        ],
    ),
    ("UG", &[("UG-C", "Central"), ("UG-N", "Northern"), ("UG-W", "Western")]),
    ("ML", &[("ML-10", "Tombouctou Region")]),
    ("RE", &[("FR-974", "Réunion")]),
    (
        "LB",
        &[
            ("LB-BH", "Mohafazat Baalbek-Hermel"),
            ("LB-BI", "Mohafazat Beqaa"),
            ("LB-BA", "Beyrouth"),
            ("LB-AS", "Mohafazat Liban-Nord"),
            ("LB-JA", "Mohafazat Liban-Sud"),
            ("LB-JL", "Mohafazat Mont-Liban"),
            ("LB-NA", "Mohafazat Nabatiye"),
        ],
    ),
    (
        "MN",
        &[
            ("MN-035", "Orhon Aymag"),
            ("MN-037", "Darhan-Uul Aymag"),
            ("MN-039", "Hentiy Aymag"),
            ("MN-041", "Hovsgol Aymag"),
            ("MN-043", "Hovd"),
            ("MN-046", "Uvs Aymag"),
            ("MN-047", "Central Aymag"),
            ("MN-049", "Selenge Aymag"),
            ("MN-051", "Suhbaatar Aymag"),
            ("MN-053", "Omnogovi Province"),
            ("MN-055", "South Khangay"),
            ("MN-057", "Dzavhan Aymag"),
            ("MN-059", "Dundgovĭ Aymag"),
            ("MN-061", "Dornod Aymag"),
            ("MN-063", "East Gobi Aymag"),
            ("MN-064", "Govĭ-Sumber"),
            ("MN-065", "Govĭ-Altay Aymag"),
            ("MN-067", "Bulgan"),
            ("MN-069", "Bayanhongor Aymag"),
            ("MN-071", "Bayan-Olgiy Aymag"),
            ("MN-073", "Arhangay Aymag"),
            ("MN-1", "Ulan Bator"),
        ],
    ),
    ("MO", &[("CN-MO", "Macao")]),
    (
        "BY",
        &[
            ("BY-BR", "Brestskaja oblast'"),
            ("BY-HO", "Gomel'skaja oblast'"),
            ("BY-HM", "Gorod Minsk"),
            ("BY-HR", "Grodnenskaja oblast'"),
            ("BY-MA", "Mogilevskaja oblast'"),
            ("BY-MI", "Minskaja oblast'"),
            ("BY-VI", "Vitebskaja oblast'"),
        ],
    ),
    ("MQ", &[("FR-972", "Martinique")]),
    ("PK", &[("PK-PB", "Punjab")]),
    (
        "PS",
        &[
            ("Area A", "Area A"),
            ("Area B", "Area B"),
            ("Judea and Samaria", "Judea and Samaria"),
        ],
    ),
    ("JE", &[("JE-1", "Jersey")]),
    ("IM", &[("IM-1", "Isle of Man")]),
    ("UM", &[("UM-1", "United States Minor Outlying Islands")]),
    (
        "KZ",
        &[
            ("KZ-10", "Abai"),
            ("KZ-75", "Almaty"),
            ("KZ-19", "Almaty Oblysy"),
            ("KZ-11", "Aqmola Oblysy"),
            ("KZ-15", "Aktyubinskaya Oblast’"),
            ("KZ-71", "Astana"),
            ("KZ-23", "Atyrau Oblysy"),
            ("KZ-27", "West Kazakhstan"),
            ("KZ-47", "Mangistauskaya Oblast’"),
            ("KZ-55", "Pavlodar Region"),
            ("KZ-35", "Qaraghandy Oblysy"),
            ("KZ-39", "Qostanay Oblysy"),
            ("KZ-43", "Qyzylorda Oblysy"),
            ("KZ-63", "East Kazakhstan"),
            ("KZ-79", "Shymkent"),
            ("KZ-59", "North Kazakhstan"),
            ("KZ-61", "Turkistan"),
            ("KZ-62", "Ulytau Audany"),
            ("KZ-31", "Zhambyl Oblysy"),
            ("KZ-33", "Zhetysu"),
        ],
    ),
    (
        "ST",
        &[
            ("ST-01", "Agua Grande"),
            ("ST-02", "Cantagalo"),
            ("ST-03", "Caue District"),
            ("ST-04", "Lemba District"),
            ("ST-05", "Lobata District"),
            ("ST-06", "Me-Zochi District"),
            ("ST-P", "Principe"),
        ],
    ),
    (
        "LI",
        &[
            ("LI-01", "Balzers"),
            ("LI-02", "Eschen"),
            ("LI-03", "Gamprin"),
            ("LI-04", "Mauren"),
            ("LI-05", "Planken"),
            ("LI-06", "Ruggell"),
            ("LI-07", "Schaan"),
            ("LI-08", "Schellenberg"),
            ("LI-09", "Triesen"),
            ("LI-10", "Triesenberg"),
            ("LI-11", "Vaduz"),
        ],
    ),
    (
        "OM",
        &[
            ("OM-DA", "Interior"),
            ("OM-BU", "Buraymi"),
            ("OM-WU", "Central"),
            ("OM-ZA", "Dhahira"),
            ("OM-BJ", "South Batina"),
            ("OM-SJ", "Southeastern"),
            ("OM-MA", "Muscat"),
            ("OM-MU", "Musandam"),
            ("OM-BS", "North Batina"),
            ("OM-SS", "Northeastern"),
            ("OM-ZU", "Dhofar"),
        ],
    ),
    (
        "NA",
        &[
            ("NA-ER", "Erongo"),
            ("NA-HA", "Hardap"),
            ("NA-KA", "Karas"),
            ("NA-KE", "Kavango East"),
            ("NA-KW", "Kavango West"),
            ("NA-KH", "Khomas"),
            ("NA-KU", "Kunene"),
            ("NA-OW", "Ohangwena"),
            ("NA-OH", "Omaheke"),
            ("NA-OS", "Omusati"),
            ("NA-ON", "Oshana"),
            ("NA-OT", "Oshikoto"),
            ("NA-OD", "Otjozondjupa"),
            ("NA-CA", "Zambezi"),
        ],
    ),
    (
        "VN",
        &[
            ("VN-07", "Tuyên Quang"),
            ("VN-02", "Lào Cai"),
            ("VN-69", "Thái Nguyên"),
            ("VN-68", "Phú Thọ"),
            ("VN-56", "Bắc Ninh"),
            ("VN-66", "Hưng Yên"),
            ("VN-HP", "Hải Phòng"),
            ("VN-18", "Ninh Bình"),
            ("VN-25", "Quảng Trị"),
            ("VN-DN", "Đà Nẵng"),
            ("VN-29", "Quảng Ngãi"),
            ("VN-30", "Gia Lai"),
            ("VN-34", "Khánh Hòa"),
            ("VN-35", "Lâm Đồng"),
            ("VN-33", "Đắk Lắk"),
            ("VN-SG", "Hồ Chí Minh"),
            ("VN-39", "Đồng Nai"),
            ("VN-37", "Tây Ninh"),
            ("VN-CT", "Cần Thơ"),
            ("VN-49", "Vĩnh Long"),
            ("VN-45", "Đồng Tháp"),
            ("VN-59", "Cà Mau"),
            ("VN-44", "An Giang"),
            ("VN-HN", "Hà Nội"),
            ("VN-26", "Thừa Thiên-Huế"),
            ("VN-01", "Lai Châu"),
            ("VN-71", "Điện Biên"),
            ("VN-05", "Sơn La"),
            ("VN-09", "Lạng Sơn"),
            ("VN-13", "Quảng Ninh"),
            ("VN-21", "Thanh Hóa"),
            ("VN-22", "Nghệ An"),
            ("VN-23", "Hà Tĩnh"),
            ("VN-04", "Cao Bằng"),
        ],
    ),
    (
        "NP",
        &[
            ("NP-P3", "Bāgmatī"),
            ("NP-P4", "Gaṇḍakī"),
            ("NP-P6", "Karṇālī"),
            ("NP-P1", "Koshī"),
            ("NP-P5", "Lumbinī"),
            ("NP-P2", "Madhesh"),
            ("NP-P7", "Sudūrpashchim"),
        ],
    ),
    (
        "BA",
        &[
            ("BA-BIH", "Federation of Bosnia and Herzegovina"),
            ("BA-SRP", "Republika Srpska"),
            ("BA-BRC", "Brčko District"),
        ],
    ),
    (
        "CY",
        &[
            ("CY-06", "Kyrenia"),
            ("CY-04", "Famagusta"),
            ("CY-03", "Larnaca"),
            ("CY-01", "Nicosia"),
            ("CY-02", "Limassol"),
            ("CY-05", "Paphos"),
        ],
    ),
    (
        "PY",
        &[
            ("PY-16", "Upper Paraguay"),
            ("PY-10", "Upper Parana"),
            ("PY-13", "Amambay"),
            ("PY-ASU", "Asuncion"),
            ("PY-19", "Boqueron"),
            ("PY-5", "Caaguazu"),
            ("PY-6", "Caazapa"),
            ("PY-14", "Canindeyu"),
            ("PY-11", "Central"),
            ("PY-1", "Concepcion"),
            ("PY-3", "Cordillera"),
            ("PY-4", "Guaira"),
            ("PY-7", "Itapua"),
            ("PY-8", "Misiones"),
            ("PY-12", "Neembucu"),
            ("PY-9", "Paraguari"),
            ("PY-15", "President Hayes"),
            ("PY-2", "Saint Peter"),
        ],
    ),
    (
        "GE",
        &[
            ("GE-AB", "Abkhazia"),
            ("GE-AJ", "Ajaria"),
            ("GE-GU", "Guria"),
            ("GE-IM", "Imereti"),
            ("GE-KA", "K'akheti"),
            ("GE-KK", "Kvemo Kartli"),
            ("GE-MM", "Mtskheta-Mtianeti"),
            ("GE-RL", "Rach'a-Lechkhumi-Kvemo Svaneti"),
            ("GE-SZ", "Samegrelo-Zemo Svaneti"),
            ("GE-SJ", "Samtskhe-Javakheti"),
            ("GE-SK", "Shida Kartli"),
            ("GE-TB", "Tbilisi"),
        ],
    ),
];
pub fn country_name(code: &str) -> &'static str {
    COUNTRY_NAMES.iter().find(|(c, _)| *c == code).map(|(_, n)| *n).unwrap_or("")
}
pub fn subdivision_name(
    country_code: &str,
    subdivision_code: &str,
) -> Option<&'static str> {
    SUBDIVISION_NAMES
        .iter()
        .find(|(c, _)| *c == country_code)
        .and_then(|(_, subs)| subs.iter().find(|(s, _)| *s == subdivision_code))
        .map(|(_, n)| *n)
}
